<script type="text/javascript">
$(document).ready(function(){	
	$("#flex1").flexigrid
			(
			{
			url: '<?=APPLICATION_URL_ADMIN."testimonial/generategrid"?>',
			dataType: 'json',
			colModel : [
				{display: 'S.No.', name : '', width : 30, sortable : false, align: 'left'},
				{display: 'Name', name : 'name', width : 450, sortable : true, align: 'left'},
				{display: 'Company', name : 'company', width : 200, sortable : true, align: 'left'},
				{display: 'Designation', name : 'designation', width : 150, sortable : true, align: 'left'},
				{display: 'Edit', name : '', width : 30, sortable : false, align: 'center'},
				{display: 'Delete', name : '', width : 30, sortable : false, align: 'center'}		
				],						
			searchitems : [
				{display: 'Name', name : 'name', isdefault:true},				
				{display: 'Company', name : 'company'}
				],
			sortname: "company",
			sortorder: "asc",
			usepager: true,
			title: 'Testimonials',
			useRp: true,
			rpOptions: ['20','30','40','10'],
			rp: 10,
			showTableToggleBtn: true,
			singleSelect : true,
			width: 1140,
			height: 290,
			autowidth:false
			}
			);   
	
});
function sortAlpha(com)
{ 
	jQuery('#flex1').flexOptions({newp:1, params:[{name:'letter_pressed', value: com},{name:'qtype',value:$('select[ta=qtype]').val()}]});
	jQuery("#flex1").flexReload(); 
}
</script>


<table width="100%" cellpadding="0" cellspacing="0" align="center">
<tr>
<td align="left" valign="top">
<!--<img src="../../../../../upload/banners/slider2.jpg" width="250" height="150" />-->

<table id="flex1" style="display:none;padding:0px;margin:0px;" width="100%" align="center"></table></td>
</tr>
</table>


