<?php
	$r=$this->result;
	//echo $r['name'];
?>
<div id="big_box" align="center" >
 <form name="frm_certi" id="frm_certi" action="" method="post">
<div>
<table width="800" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td valign="top" width="800" height="350" style="background-repeat:no-repeat;" background="<?=IMAGES_URL?>Receipt_Share_Certificate.jpg">
<table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td height="150"></td>
    </tr>
  <tr>
    <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="19%">&nbsp;</td>
        <td width="62%" align="left"style="padding-top:5PX;"><b> <? echo $r['name'];?>,&nbsp;<? echo $r['address'];?></b>            </td>
        <td width="19%" align="left"style="padding-top:5PX;"><b><? echo $r['address'];?></b></td>
      </tr>
    </table>
	</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td valign="top"><table width="100%" border="1" cellspacing="0" cellpadding="0">
      <tr>
        <td width="18%">&nbsp;</td>
        <td width="17%" align="left" style="padding-top:8PX;"><b><? echo $r['profileId'];?></b></td>
        <td width="21%" align="left" style="padding-top:8PX;"><b><? echo $r['profileId'];?></b></td>
        <td width="26%" align="left" style="padding-top:8PX;"><b><? echo $r['profileId'];?></b></td>
        <td width="18%"><b><? echo $r['profileId'];?></b></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><table width="100%" border="1" cellspacing="0" cellpadding="0">
      <tr>
        <td width="23%">&nbsp;</td>
        <td width="59%" align="left" style="padding-top:4PX;"><b><? echo $r['profileId'];?></b></td>
        <td width="18%"><b><? echo $r['profileId'];?></b></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>

	</td>
  </tr>
  <tr>
    <td>&nbsp;
	</td>
  </tr>
</table>
</div>
<br />

<div>
<table width="800" height="705" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td valign="top" width="800" height="350" style="background-repeat:no-repeat;" background="<?=IMAGES_URL?>Share_Certificate.jpg"><table width="100%" border="1" cellspacing="0" cellpadding="0">
      <tr>
        <td height="312"></td>
      </tr>
      <tr>
        <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="22%">&nbsp;</td>
              <td align="left"style="padding-top:5PX;"><b> <? echo $r['name'];?>,&nbsp;<? echo $r['address'];?></b> </td>
              </tr>
        </table></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><table width="100%" border="1" cellspacing="0" cellpadding="0">
          <tr>
            <td width="19%">&nbsp;</td>
            <td width="81%" align="left" style="padding-top:10PX;"><b><? echo $r['profileId'];?></b></td>
            </tr>
        </table></td>
      </tr>
      <tr>
        <td valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td><table width="100%" border="1" cellspacing="0" cellpadding="0">
          <tr>
            <td width="30%">&nbsp;</td>
            <td width="70%" align="left" style="padding-top:10px;"><b><? echo $r['profileId'];?></b></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><table width="100%" border="1" cellspacing="0" cellpadding="0">
          <tr>
            <td width="21%">&nbsp;</td>
            <td width="51%" align="left" style="padding-top:15px;"><b><? echo $r['profileId'];?></b></td>
            <td width="28%" align="left" style="padding-top:15px;"><b><? echo $r['profileId'];?></b></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><table width="100%" border="1" cellspacing="0" cellpadding="0">
          <tr>
            <td width="21%">&nbsp;</td>
            <td width="30%" align="left" style="padding-top:12px;"><b><? echo $r['profileId'];?></b></td>
            <td width="49%" align="left" style="padding-top:12px;"><b><? echo $r['profileId'];?></b></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><table width="100%" border="1" cellspacing="0" cellpadding="0">
          <tr>
            <td width="38%">&nbsp;</td>
            <td width="62%" align="left" style="padding-top:10px;"><b><? echo $r['profileId'];?></b></td>
            </tr>
        </table></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><table width="100%" border="1" cellspacing="0" cellpadding="0">
          <tr>
            <td width="15%">&nbsp;</td>
            <td width="85%" align="left" style="padding-top:8px;"><b><? echo $r['profileId'];?></b></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table></td>
    </tr>
</table>
</div>
</form>
</div>