<?php 
global $mySessionFront;
$db=new Db();
?>

<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
				$('#paging_container1').pajinate();
			});
</script>
<script type="text/javascript" language="javascript">
	
	$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
        $('li#mypro').removeClass('active');
        });	 
		  
</script>
<?php 
$res=$this->Job_Seeker_Data;
$res1=$this->Company_Details;
?>
<div class="container job_apply">


<!--======================================== User Profile ===================================-->
<script language = "Javascript">
function resume(){
	alert('Hello...');
	var user_id=$("#user_id").val();
	alert(user_id);
	var resume_file=$("#resume_file").val();
	alert(resume_file);
	
	document.getElementById('resume').innerHTML="<img src='<?=IMAGES_URL?>load.gif' border='0'>";
	$.ajax({ url: "<?php echo $this->url(array('controller'=>'dashboard','action'=>'resumeedit'),'default',true);?>",
	type: "POST",
	//data: ({user_id: user_id, user_fname: user_fname, user_lname: user_lname}),
		success: function(data){			
		$("#resume").html(data);			
		}
	});
//alert('hello');    baseinfo
}
</script>

<script type="text/javascript" >
 $(document).ready(function() { 
		
            $('#photoimg').live('change', function()			{ 
			           $("#preview").html('');
			    $("#preview").html('<img src="<?=IMAGES_URL?>load.gif" alt="Uploading...."/>');
			$("#imageform").ajaxForm({
						target: '#preview'
		}).submit();
		
			});
        }); 
</script>
<div class="content_left" id="edit_user_data">
            	<div class="profile_head">
                	<div class="img">
                    <?php 
						if($res['user_image']=='')
						{
						?>
							<img width="167" height="167"  src="<?=IMAGES_URL?>no-avator.png" >
                        <?php }else{ ?>
							<img width="167" height="167" src="<?=ADMIN_IMG?>user_pic/<?php echo $res['user_image']?>" alt="">
						<? }?>
                    </div>
                    
                    <div class="info">
                    	<h1 class="title captl"><? echo $res['user_fname'].' '.$res['user_lname']?></h1>
                    <?
                    	$Credit_Qry="SELECT * FROM tbl_users where user_id ='".$mySessionFront->user['FrontUserId']."'";
						//prd($Credit_Qry);
						$Job_Credit_Result=$db->runQuery($Credit_Qry);
						
						$User_Exp_Activ= "SELECT * FROM tbl_user_experience WHERE is_current ='1' and user_id = '".$res['user_id']."'";
						$User_Exp_User_Exp_Activ_Data = $db->runQuery($User_Exp_Activ);
						//prd($User_Exp_User_Exp_Activ_Dat);
					?>   
<h3><?php echo @$User_Exp_User_Exp_Activ_Data[0]['position']?> at <?php echo @$User_Exp_User_Exp_Activ_Data[0]['company']?></h3>
                       
                        
                        <p class="font12 exp_edu1"><?php echo $res['user_city']?>, <?php echo $res['country_name']?> <span>|</span> <!--Information Technologies and Services--><?php echo $res['category_title']?></p>
                        <ul class="exp_edu font12">
                        	<li><span>Current</span> <?php echo @$User_Exp_User_Exp_Activ_Data[0]['company']?></li>
                        </ul>
                    </div>
                    <div class="clr"></div>
                </div>
                
                <div class="profiel_list">
                <div id="preview" style="display:block; padding-bottom:5px;"></div>
                	
<!--========================= User Profile ==========================-->
                    <div class="block1">
                    	<h2 class="floatleft title">Profile Summery</h2>
                        <!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                        <div class="clr"></div>

                        <div class="block1_content">
                        	<?php echo $res['user_profile_summary']?>
                            <!--<ul class="bullet1">
                            	<li>AAA</li>
                            </ul>-->
                        </div>
                    </div>
<!--========================= End of User Profile ==========================-->


<!--========================= Experience ==========================-->
                    
                        
                       <div class="block1" id="experience">
    <h2 class="floatleft title">Experience</h2>
    
    <div class="clr"></div>
    <div class="block1_content">
        <ul class="bullet2">
            <?php 
                $i=1;
                foreach($this->User_Exp_All_Val as $User_Multi_Experience) {
            ?>
            <li>
                <div class="number"><?=@$i++;?></div>
                
                <div class="info">
                    <h2><?php echo @$User_Multi_Experience['position']?></h2>
                    <h3><?php echo @$User_Multi_Experience['company']?></h3>
                    <p class="font12"><?php echo @$User_Multi_Experience['location']?> <span class="pipe_space">|</span> 
                    <?php echo @$User_Multi_Experience['employment_period_from']?> &ndash; <?php echo $User_Multi_Experience['employment_period_to']?></p>
                    <h4>Job Responsibilities</h4>
                    <p class="font12"><?php echo @$User_Multi_Experience['responsibility']?></p>
                </div>
                <? 
            $Company_Logo_Qry = "select user_image from tbl_users where user_company='".$User_Multi_Experience['company']."'";
            //prd($Company_Logo_Qry);
            $Company_Logo_Qry_Data=$db->runQuery("$Company_Logo_Qry");
            //prd($Company_Logo_Qry_Data); //user_company
            foreach($Company_Logo_Qry_Data as $Company_Logo)
            {	
       ?>
                <div class="img">
                	<img width="112" height="70" src="<?=ADMIN_IMG?>user_pic/<?php echo @$Company_Logo['user_image']?>" alt="">
                </div>
                <div class="clr"></div>
                <?php } ?>
            </li>
            <?php } ?>
        </ul>
    </div>
</div> 
<!--========================= End of Experience ==========================-->


                    <div class="block1">
                    	<h2 class="floatleft title">Skills &amp; Expertise</h2>
                        <!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<p class="font16"><?php echo $res['user_skills_n_expertise']?></p>
                        </div>
                    </div>
                    
                    <!--<div class="block1">-->
                    <div class="block1" id="education">
                    	<h2 class="floatleft title">Education</h2>

                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="bullet2">
                            	<?php 
									$i=1;
									foreach($this->Education_Dashboard as $User_Education) {
								?>
                                <li><div class="" style="float:right;">

                                </div>
                                	<div class="number"><?=$i++;?></div>
                                    
                                    <div class="info1">
                                    	<h2><?php echo $User_Education['university']?></h2>
                                        <h3><?php echo $User_Education['education_title']?></h3>
                                 <p class="font12">From<?php echo $User_Education['starting_year']?> to <?php echo $User_Education['finishing_year']?></p>
                                	 <?php 
										if($User_Education['is_heighest']=='1')
										{
									?>
									<p class="font12">Is Heighest  <b><?php echo 'Yes';?></b></p>
                       				 <?php }else{ ?>
										<p class="font12">Is Heighest  <b><?php echo 'No';?></b></p>
									<? }?>
                                 
                                    </div>
                                    
                                    <div class="clr"></div>
                                </li>
                                <? } ?> 
                            </ul>
                        </div>
                    </div>
                    
                    <div class="block1">
                    	<h2 class="floatleft title">Personal Information</h2>
                        <!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="view_list">
                            	<li>
                                	<div class="label">Date of Birth</div>
                                    <div class="info"><?php echo date("d M Y", strtotime($res['user_dob']))?></div>
                                </li>
                                <li>
                                	<div class="label">Marital Status</div>
                                    <div class="info"><?php echo $res['user_marital_status']?></div>
                                </li>
                                <li>
                                	<div class="label">Email Address</div>
                                    <div class="info"><?php echo $res['user_email']?></div>
                                </li>
                                <li>
                                	<div class="label">Phone Number</div>
                                    <div class="info"><?php echo $res['user_phone']?></div>
                                </li>
                                <li>
                                	<div class="label">Gender</div>
                                    <div class="info"><?php echo $res['user_gender']?></div>
                                </li>
                                <li>
                                	<div class="label">Nationality</div>
                                    <div class="info"><?php echo $res['nation_title']?></div>
                                </li>
                                <li>
                                	<div class="label">Career Level</div>
                                    <div class="info"><?php echo $res['career_level_title']?></div>
                                </li>
                            </ul>
                            <div class="clr"></div>
                        </div>
                    </div>
                    
                </div>
            </div>
<!--===================================== End of User Profile ================================-->            
            
<!--============================================ Side Bar Job Seeker =========================================-->
<!--============================================ Side Bar Job Seeker =========================================-->
            <div class="content_right">
            	<div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyPosted_Job=$this->Emp_Posted_Job;
							$MyTotalSave=$this->Emp_SaveJobs; 
							$MyTotalNoti=$this->Emp_Job_Noti;
							$Resumes_Total=$this->Resumes_Data_Total;
						?>
                    <ul>
   <li><a href="<?=APPLICATION_URL?>company/companypostedjob"><span class="number number_green"><?php echo $MyPosted_Job['TotalApply']?></span>Jobs Posted</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companysavejob"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companymsg"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companyresumes"><span class="number"><?php echo $Resumes_Total['Total_Resumes']?></span> Resumes</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
                <div class="block credit_blnc font12">
                	<h2 class="title">Credit Balance</h2>
                    <div class="in_block1">
                    	<h3>Job Posting Credits</h3>
                        
                        <div class="in_block1_content">
                            <ul class="bullet6 font12">
                                <li>
                                	Normal Job Postings: <?php echo $res1['user_jobs_available'] ?><br />
                                    <?php 
										if(@$res1['user_jobs_expire_on']=='0000-00-00')
										{
									?>
                                    (Expire N/a)
                                    <? }else{ ?>
                                    (Expire <?php echo date("d-M-Y", strtotime($res1['user_jobs_expire_on'])) ?>)
                                    <? } ?>
                                </li>
                                
                                <li>
                                	premium Job Postings: <?php echo $res1['user_featured_jobs_available'] ?><br />
                                    <?php 
										if(@$res1['user_jobs_expire_on']=='0000-00-00')
										{
									?>
                                    (Expire N/a)
                                    <? }else{ ?>
                                    (Expire <?php echo date("d-M-Y", strtotime($res1['user_featured_jobs_expire_on'])) ?>)
                                	<? } ?>
                                </li>
                                
                                <li><a href="<?=APPLICATION_URL?>subscription/jobcredits" class="blue">Add job posting credits</a></li>
                                <li><a href="<?=APPLICATION_URL?>dashboard/mycredits" class="blue">View Credit </a></li>
                                <li><a href="<?=APPLICATION_URL?>dashboard/paymenthistory" class="blue">View Payment History</a></li>
                            </ul>
<!--<p class="align-right"><a href="<?=APPLICATION_URL?>subscription/jobcredits" class="maroon underline">Buy Job Posting Credits</a></p>-->
                        </div>
                    </div>
                    <div class="in_block1">
                        <h3>CV Search Credits</h3>
                        <div class="in_block1_content">                    	
                            <ul class="bullet6 font12">
                                <li>
                                	Global Search<br>
                                    <?php 
										if(@$res1['user_resume_membership_expires_on']=='0000-00-00')
										{
									?>
                                    (Expire N/a)
                                    <? }else{ ?>
                                    (Expire <?php echo date("d-M-Y", strtotime($res1['user_featured_jobs_expire_on'])) ?>)
                                    <? } ?>
                                </li>
                               
                                <li><a href="<?=APPLICATION_URL?>subscription/cvcredits" class="blue">Subscribe to CV Search</a></li>
                            </ul>
                        </div>
                    </div>
                    <ul class="bullet6 font12">
                        <li><a href="<?=APPLICATION_URL?>dashboard/paymenthistory" class="blue">View Payment History</a></li>
                        <li><a href="<?=APPLICATION_URL?>dashboard/mycredits" class="blue">View Credit</a></li>
                    </ul>
                </div>
            </div>
<!--========================================== End Side Bar Job Seeker =========================================-->
           
            <div class="clr"></div>
        </div>


