<?php 
global $mySessionFront;
$db=new Db();

$akash=$this->user_id;
$aid=@$akash['user_id'];
?>

<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate_1.js" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
	$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
        $('li#mypro').removeClass('active');
        });	 
		  
</script>

<script language = "Javascript">
function sendmsg(){
	//alert('Hello...');
	var UserMsg=$("#UserMsg").val();
	alert(UserMsg);
	var sendto=$("#sendto").val();
	alert(sendto);
	
	var sender=$("#sender").val();
	alert(sender);
	document.getElementById('message').innerHTML="<img src='<?=APPLICATION_URL_ADMIN?>images/load.gif' border='0'>";
	
	$.ajax({ url: "<?php echo $this->url(array('controller'=>'user','action'=>'sendmsg'),'default',true);?>",
	type: "POST",
	data: ({msgid: msgid, sendto: sendto,UserMsg: UserMsg}),
	success: function(data){			
	//$("#showDiv").html(data);
	$("#message").html(data);			
	}});
//alert('hello');
}

</script>



<script>
$(document).ready(function(){
	$('#paging_container1').pajinate();
				
});
</script>
<script>
$(document).ready(function(){
	$('#MyInbox').click(function ( event ) {
        $("#MyInbox").addClass("active");
        $("#MySentbox").removeClass("active");
        event.preventDefault(); 
       
   });
    
	$('#MySentbox').click(function ( event ) {
        $("#MySentbox").addClass("active");
        $("#MyInbox").removeClass("active");
        event.preventDefault(); 
        
   });			
			
});
			

</script>
<script src="<?=JS_URL?>ddaccordion.js"></script>
<script type="text/javascript">


ddaccordion.init({
	headerclass: "submenuheader", //Shared CSS class name of headers group
	contentclass: "submenu", //Shared CSS class name of contents group
	revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click", "clickgo", or "mouseover"
	mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
	collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
	defaultexpanded: [], //index of content(s) open by default [index1, index2, etc] [] denotes no content
	onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
	animatedefault: false, //Should contents open by default be animated into view?
	persiststate: true, //persist state of opened contents within browser session?
	toggleclass: ["", ""], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
	togglehtml: ["suffix", "<img src='images/drop-down-erro2.jpg' class='statusicon' />", "<img src='images/drop-down-erro.jpg' class='statusicon' />"], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
	animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
	oninit:function(headers, expandedindices){ //custom code to run when headers have initalized
		//do nothing
	},
	onopenclose:function(header, index, state, isuseractivated){ //custom code to run whenever a header is opened or closed
		//do nothing
	}
})


</script>


<div class="container job_apply">
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->
    <div class="content_left">
        	<?php $res=$this->Company_Data; ?> 
            	<div class="job_head">
                <div class="img">
                  		<?php 
							if($res['user_image']=='')
							{
						?>
							<img width="124" height="118"  src="<?=IMAGES_URL?>no-avator.png" >
                        <?php }else{ ?>
							<img width="124" height="118" src="<?=ADMIN_IMG?>user_pic/<?php echo $res['user_image']?>" alt="">
						<? }?>
				</div>
                <div class="info">
                    <h1 class="title captl"><?php echo $res['user_company']?></h1>
                    <p class="font12"><?php echo $res['user_city']?>, <?php echo $res['country_name']?></p>
                    <p class="job_title"><span class="blue"><?php echo $res['category_title']?></span></p>
                    <div class="floatleft"><a href="<?=APPLICATION_URL?>subscription/index" class="blue">Add more Credits</a></div>
                    <div class="floatright"><a href="<?=APPLICATION_URL?>job/postjob" class="blue">Post New Job</a></div>
				</div>
                	<div class="clr"></div>
		</div>
        
        
            
        <div class="list">
        			<div id="ajaxDiv" style="visibility:hidden;"></div>
                    
                	<h1 class="title captl floatleft">Notifications</h1>
                    
                    <div class="clr"></div>
                    
                   
                   
                   
                    <ul class="content_tabs">
                    	<li class="active" id="MyInbox" onclick=""><a href="#">Inbox</a></li>
                        <!--<li class="" id="MySentbox"><a href="#" >Sent</a></li>-->
                    </ul>
                    <div class="clr"></div>
                    
                    <!--==========================================================-->
                   		<div class="font11">
                        	<div id="paging_container1">
                                <ul class="ntfcn_list content">
                                  
                                   <? if(is_array($this->CompanyMsg) && count($this->CompanyMsg) > 0) {
                                        foreach($this->CompanyMsg as $MyInbox) { ?>	 
                                         <li class="">
                                            
                                    <div class="submenuheader">
                                        <?php if($MyInbox['is_read']==0)
                                             {
                                        ?>
                               <div style="font-weight:bold;" onclick="getajax('<?=BASE_PATH?>user/isread/id/<?php echo $MyInbox['id']?>','ajaxDiv');">
                                            <?php }else{ ?>
                                            <div>
                                            <?php } ?>
                                            
                                                <?=$MyInbox['user_fname']?> <?=$MyInbox['user_lname']?> 
                                                <span style="margin-left:20px;"><?=substr($MyInbox['subject'],0,10)?>...</span>
                                                <span style="margin-left:20px;"><?=substr($MyInbox['message'],0,45)?>...</span>
                                                <span style="margin-left:20px;"><?=$MyInbox['sent_on']?></span>
                                            </div> 
                                    
                                     </div>
                                      <div class="submenu" id="message"> 
                                      		<br />
                                            <div class="" ><?=$MyInbox['message']?></div>
                                            <br />
                                <div style="border-top:1px solid #CCC;" >
<form name="user_msg" id="user_msg" action="<?php echo $this->url(array('controller'=>'company', 'action'=>'sendmsg'), 'default', true)?>" method="post">
    <input type="hidden" name="subject" id="subject" value="<?=$MyInbox['subject']?>" />
    <input type="hidden" name="sendto" id="sendto" value="<?=$MyInbox['from']?>" />
    <input type="hidden" name="sender" id="sender" value="<?=$mySessionFront->user['FrontUserId'] ?>" />
    <textarea  cols="" rows="" class="mytextarea" name="UserMsg" id="UserMsg" ></textarea>
    <!--<input type="button"  value="Sent Msg" class="apply_btn" onclick="sendmsg();">-->
    <input type="submit"  value="Sent Msg" class="apply_btn" onclick="">
</form>
								 </div> 
                                 
                                 
                                    </li>
                                 <?php } ?>
                                 <?php } else {?> 
                                    <li class="unread">
                                        <div class="title">No Notification Found</div>
                                    </li>
                                <?php } ?>
                                </ul>
                                <div class="page_navigation" style="padding-left:125px;"></div>	
                             </div>
                    	</div>
                        
                    <!--==========================================================-->
                   
                 	</div>
        
                
    </div>
    <!--============================================ Side Bar Employee ===========================================-->
			<div class="content_right">
            	<div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyPosted_Job=$this->Emp_Posted_Job;
							$MyTotalSave=$this->Emp_SaveJobs; 
							$MyTotalNoti=$this->Emp_Job_Noti;
							$Resumes_Total=$this->Resumes_Data_Total;
						?>
                    <ul>
   <li><a href="<?=APPLICATION_URL?>company/companypostedjob"><span class="number number_green"><?php echo $MyPosted_Job['TotalApply']?></span>Jobs Posted</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companysavejob"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companymsg"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companyresumes"><span class="number"><?php echo $Resumes_Total['Total_Resumes']?></span> Resumes</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
                <div class="block credit_blnc font12">
                	<h2 class="title">Credit Balance</h2>
                    <div class="in_block1">
                    	<h3>Job Posting Credits</h3>
                        
                        <div class="in_block1_content">
                            <ul class="bullet6 font12">
                                <li>
                                	Normal Job Postings: <?php echo $res['user_jobs_available'] ?><br />
                                    <?php 
										if(@$res['user_jobs_expire_on']=='0000-00-00')
										{
									?>
                                    (Expire N/a)
                                    <? }else{ ?>
                                    (Expire <?php echo date("d-M-Y", strtotime($res['user_jobs_expire_on'])) ?>)
                                    <? } ?>
                                </li>
                                
                                <li>
                                	premium Job Postings: <?php echo $res['user_featured_jobs_available'] ?><br />
                                    <?php 
										if(@$res['user_jobs_expire_on']=='0000-00-00')
										{
									?>
                                    (Expire N/a)
                                    <? }else{ ?>
                                    (Expire <?php echo date("d-M-Y", strtotime($res['user_featured_jobs_expire_on'])) ?>)
                                	<? } ?>
                                </li>
                                
                                <li><a href="<?=APPLICATION_URL?>subscription/jobcredits" class="blue">Add job posting credits</a></li>
                                <li><a href="<?=APPLICATION_URL?>dashboard/mycredits" class="blue">View Credit </a></li>
                                <li><a href="<?=APPLICATION_URL?>dashboard/paymenthistory" class="blue">View Payment History</a></li>
                            </ul>
<!--<p class="align-right"><a href="<?=APPLICATION_URL?>subscription/jobcredits" class="maroon underline">Buy Job Posting Credits</a></p>-->
                        </div>
                    </div>
                    <div class="in_block1">
                        <h3>CV Search Credits</h3>
                        <div class="in_block1_content">                    	
                            <ul class="bullet6 font12">
                                <li>
                                	Global Search<br>
                                    <?php 
										if(@$res['user_resume_membership_expires_on']=='0000-00-00')
										{
									?>
                                    (Expire N/a)
                                    <? }else{ ?>
                                    (Expire <?php echo date("d-M-Y", strtotime($res['user_featured_jobs_expire_on'])) ?>)
                                    <? } ?>
                                </li>
                               
                                <li><a href="<?=APPLICATION_URL?>subscription/cvcredits" class="blue">Subscribe to CV Search</a></li>
                            </ul>
                        </div>
                    </div>
                    <ul class="bullet6 font12">
                        <li><a href="<?=APPLICATION_URL?>dashboard/paymenthistory" class="blue">View Payment History</a></li>
                        <li><a href="<?=APPLICATION_URL?>dashboard/mycredits" class="blue">View Credit</a></li>
                    </ul>
                </div>
            </div>	
<!--========================================== End Side Bar Employee =========================================-->
    <div class="clr"></div>
</div>

