<?php global $mySessionFront;?>

<!--============================================ Java Script & Css ===========================================-->	
<script type="text/javascript" language="javascript">
	//$(document).ready(function() {
         // $('body').addClass('home');
        //});
		
	$(document).ready(function() {
        $('li').removeClass('active');
        });	
	
</script>
   
<div class="container static_page">
        	<h1 class="title">Help</h1>
        	<div class="content_left">
           	  	<div class="page_content">
                    <p></p><div class="content-left-img"><img alt="" src="images/company_img.jpg"></div>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<p></p>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
              </div>
          	</div>
            <div class="content_right">
            	<div class="block page_link">
                    <ul>
                    	<li class="active"><a href="#">About Us</a></li>
                        <li><a href="#">Testimonials</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Privacy Policies</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Company Blog</a></li>
                    </ul>
                </div>
                <div class="block ad align-center"><img width="100%" alt="" src="images/google_ad2.jpg"></div>
            </div>
            <div class="clr"></div>
        </div>