<div id="big_box" align="center" >
 <form name="Form_Memberedit" id="Form_Memberedit" action="" method="post" enctype="multipart/form-data">      
 <table width="100%" border="0" cellspacing="5" cellpadding="0" class="frmtable">
  <tr>
  <td width="17%" align="left" valign="top">Caption:</td>
  <td align="left" valign="top"><? echo $this->myform->banner_alt?></td>
  </tr> ` 
  <tr>
  <td width="17%" align="left" valign="top"> Link (with http://):</td>
  <td align="left" valign="top"><? echo $this->myform->banner_link?></td>
  </tr>  
  <tr>
  <td align="left" valign="top"> Window open:<span class="errormsg">*</span></td>
  <td align="left" valign="top"><? echo $this->myform->banner_window_open?></td>
  </tr>
  <tr>
  <td align="left" valign="top">Banner Image:</td>
  <td align="left" valign="top"><? echo $this->myform->banner_image?></td>
  </tr>
  <tr>
  	<td align="left" valign="top">&nbsp;</td>
  	<td align="left" valign="top">741px(width)  x  171px(height) for best results</td>
  	</tr>
 
  <tr>
    <td align="left" valign="top" style="font-size:11px;"><span class="errormsg">*</span> Required fields</td>
    <td align="left" valign="top"><input type="submit" name="mySubmit" id="mySubmit" value="Submit" /></td>
  </tr>  
</table>
</form>
</div>