<?
global $mySession;


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" >
<?php	
	if($this->pagetitle==''){
		$pgt  = 'Job Portal | Admin';
	} else {
		$pgt = $this->pagetitle;
	}
	$cnname = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$actname = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<head>
	<script>var APPLICATION_URL = '<? echo APPLICATION_URL?>';</script>

	<?php /*?><script language="javascript" src="<? echo JS_URL?>main.js"></script><?php */?>
	<title><?php echo $pgt;?></title>
	<link rel="stylesheet" type="text/css" href="<? echo CSS_URL?>main.css"/>
	


<link rel="stylesheet" href="<?=CSS_URL?>dhtmlgoodies_calendar.css?random=20051112" media="screen">
<script type="text/javascript" src="<?=JS_URL?>dhtmlgoodies_calendaren.js?random=20060118"></script>

<script language="javascript"> var calImagesPath='<?=APPLICATION_URL?>' </script>

<script type="text/javascript" src="<?=JS_URL?>dhtmlgoodies_calendaren.js?random=20060118"></script>
<script src="<?=JS_URL?>jquery-1.2.3.pack.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.tablednd_0_5.js" type="text/javascript"></script>


<script src="<?=JS_URL?>mygridscript.js" type="text/javascript"></script>
<script src="<?=JS_URL?>mousehold.js" type="text/javascript"></script>

<script src="<?=JS_URL?>flexigrid1.js" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="<?=CSS_URL?>flexigrid1.css" />

<script src="<?=JS_URL?>jquery-1.5.js" type="text/javascript"></script>
<script src="<?=CK_Edit?>ckeditor.js" type="text/javascript"></script>

<script language="javascript">
function checknumber(e)
{
	evt=e || window.event;
	var keypressed=evt.which || evt.keyCode;
	//alert(keypressed);
	if(keypressed!="48" &&  keypressed!="49" && keypressed!="50" && keypressed!="51" && keypressed!="52" 
		&& keypressed!="53" && keypressed!="54" && keypressed!="55" && keypressed!="8" && keypressed!="56" 
		&& keypressed!="57" && keypressed!="45" && keypressed!="46" && keypressed!="37" && keypressed!="39" 
		&& keypressed!="9")
	{
		return false;
	}
}
function checknumbercomma(e)
{
	evt=e || window.event;
	var keypressed=evt.which || evt.keyCode;
	//alert(keypressed);
	if( keypressed!="44" && keypressed!="48" &&  keypressed!="49" && keypressed!="50" && keypressed!="51" && keypressed!="52" 
		&& keypressed!="53" && keypressed!="54" && keypressed!="55" && keypressed!="8" && keypressed!="56" 
		&& keypressed!="57" && keypressed!="46" && keypressed!="37" && keypressed!="39" 
		&& keypressed!="9")
	{
		return false;
	}
}

</script>
</head>
<body>
<div style="background:url(<?=IMAGES_URL?>bg_main.png); background-repeat:repeat-x">
<table width="1150" cellpadding="0" cellspacing="0" border="0" align="center">
  <tr>
    <td align="center" valign="top">
	<table width="100%" cellpadding="0" cellspacing="0" align="center">
      <tr>
        <td align="center" valign="top"><?php include "header.phtml"; ?></td>
      </tr>     
      <tr>
        <td align="center" valign="top" height="" style="background-repeat:repeat;">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td style="background:url(<?=IMAGES_URL?>main_left1.png); background-repeat:repeat-y" width="5"><img src="<?=IMAGES_URL?>blank.gif" width="5" /></td>
			<td style="padding:0 3px; ">
			<?php
				if(isset($this->pagetitle) && !empty($this->pagetitle)) { ?>
				<div id="page_heading"><?php echo $this->pagetitle; ?></div>
			<?php } ?>
		<?php global $mySession;?>
		
        
		<div id="divError" style="padding:5px;">
	<?php if(isset($mySession->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySession->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySession->errorMsg);} ?>
    
    <?php if(isset($mySession->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySession->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySession->sucMsg); } ?>
    
    <?php if(isset($mySession->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySession->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySession->warningMsg); } ?>
</div>
		
        <table width="100%" cellpadding="0" cellspacing="0" border="0" align="center">
          <tr>
            <td align="center" valign="top"><div align="center">
			<?php if($cnname=='index' && $actname=='index') {  } else { ?><div id="innerdiv"><?php } ?>
			
			<?php echo $this->layout()->content; ?>
			<?php if($cnname=='index' && $actname=='index') {  } else { ?><br />
<br />
<br />
<br />
<br />
</div><?php } ?>
			<br />
<br />
<br />
<br />
<br />

			</div>
			</td>              
	      </tr>
        </table>
		<br />
<br />
<br />
<br />
</td>
			<td style="background:url(<?=IMAGES_URL?>main_right1.png); background-repeat:repeat-y" width="11"><img src="<?=IMAGES_URL?>blank.gif" width="11" /></td>
		  </tr>
		  
		  

		
		<tr>
			<td style="background:url(<?=IMAGES_URL?>main_left2.png); background-repeat:no-repeat" width="5"><img src="<?=IMAGES_URL?>blank.gif" width="5" /></td>
			<td style="background:url(<?=IMAGES_URL?>main_center.png); background-repeat:repeat-x" ><img src="<?=IMAGES_URL?>main_center1.png" width="7"  /></td>
			<td style="background:url(<?=IMAGES_URL?>main_right2.png); background-repeat:no-repeat" width="11"><img src="<?=IMAGES_URL?>blank.gif" width="11" /></td>
		  </tr>
		</table></td>
      </tr>
      <tr>
        <td align="left" valign="top"><?php include "footer.phtml"; ?></td>
      </tr>
    </table></td>
  </tr>
</table>
</div>
</body>
</html>