<div id="big_box" align="center" >
 <form name="Form_Memberedit" id="Form_Memberedit" action="" method="post" enctype="multipart/form-data">      
 <table width="100%" border="0" cellspacing="5" cellpadding="0" class="frmtable">
  <tr>
  <td width="17%" align="left" valign="top">Job Type:</td>
  <td align="left" valign="top"><? echo $this->myform->job_type_title?></td>
  </tr>
  <tr>
    <td align="left" valign="top" style="font-size:11px;"><span class="errormsg">*</span> Required fields</td>
    <td align="left" valign="top"><input type="submit" name="mySubmit" id="mySubmit" value="Submit" /></td>
  </tr>  
</table>
</form>
</div>