
<div class="container recruiter_page">
        	<div class="content_full">
            	<h1 class="title align-center">Online Recruitment and Employment Solutions for Employers</h1>
            	<div class="prices_cols">
                	<div class="col col1">
                    	<h2>Small</h2>
                        <div class="prices"><sub>$</sub> <span>79</span> <sup>monthly</sup></div>
                        <ul class="list">
                        	<li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                        </ul>
                        <input type="button" class="buy_btn" value="BUY NOW">
                    </div>
                    <div class="col col2">
                    	<h2>Medium</h2>
                        <div class="prices"><sub>$</sub> <span>79</span> <sup>monthly</sup></div>
                        <ul class="list">
                        	<li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                        </ul>
                        <input type="button" class="buy_btn" value="BUY NOW">
                    </div>
                    <div class="col col3">
                    	<h2>Large</h2>
                        <div class="prices"><sub>$</sub> <span>79</span> <sup>monthly</sup></div>
                        <ul class="list">
                        	<li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                            <li>XYZ Job Posting</li>
                        </ul>
                        <input type="button" class="buy_btn" value="BUY NOW">
                    </div>
                    <div class="clr"></div>
                </div>
                <div class="seperator">
                    <span class="or">or</span>
                </div>
                <div class="floatleft highlight-box2 mar-l180">
                    <h3 class="align-center">Post Jobs</h3>
                    <ul class="check_icons">
                        <li>Post jobs worldwide</li>
                        <li>Receive applicants in minutes</li>
                        <li>60-day ads available</li>
                    </ul>
                    <p class="align-right"><a href="#" class="black">More details...</a></p>
                    <a href="#" class="post_now_btn">Post Now</a>
                </div>
                <div class="floatleft highlight-box2">
                    <h3 class="align-center">Search CVs</h3>
                    <ul class="check_icons">
                        <li>Access 12,250,000 candidates</li>
                        <li>Filter CVs by 34 criteria</li>
                        <li>Hire talent quickly and easily</li>
                    </ul>
                    <p class="align-right"><a href="#" class="black">Try CV Search</a></p>
                    <a href="#" class="post_now_btn">Search Now</a>
                </div>
            </div>
            <div class="clr"></div>
        </div>