<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="topnav_div">

	<div class="menu_box_heading">Scheme</div>
		<div class="menu_box">
			<a href="<?php echo APPLICATION_URL.'scheme'; ?>">View Scheme</a><br />
			<a href="<?php echo APPLICATION_URL.'scheme/add'; ?>">Add Scheme</a><br />
		</div>
	<div class="clrboth"></div>
	<div class="menu_box_heading">Customer</div>
		<div class="menu_box">
			<a href="">View Customer</a><br />
			<a href="">Add Customer</a><br />
		</div>
	
	<div class="clrboth"></div>
	<div class="menu_box_heading">Agent</div>
		<div class="menu_box">
			<a href="">View Agent</a><br />
			<a href="">Add Agent</a><br />
		</div>
	
</td>
  </tr>
</table>