<script language="javascript">

function showPassword(obj)

{

	if(obj.checked==true)

	{

		document.getElementById('ChangePassword').style.display="block";

	}

	else

	{

		document.getElementById('ChangePassword').style.display="none";

	}

}

function getBranchEmployee(branchId)

{

	document.getElementById('EmployeeIdDiv').innerHTML="<img src='<?=APPLICATION_URL_ADMIN?>images/load.gif' border='0'>";

	$.ajax({ url: "<?php echo $this->url(array('controller'=>'agent','action'=>'getbranchemp'),'default',true);?>",

	type: "POST",

	data: ({branchId : branchId}),

	success: function(data){			

	$("#EmployeeIdDiv").html(data);			

	}});	

}

function getStatecity(stateId)

{

	document.getElementById('CityIdDiv').innerHTML="<img src='<?=APPLICATION_URL_ADMIN?>images/load.gif' border='0'>";

	$.ajax({ url: "<?php echo $this->url(array('controller'=>'agent','action'=>'getstatecity'),'default',true);?>",

	type: "POST",

	data: ({stateId : stateId}),

	success: function(data){			

	$("#CityIdDiv").html(data);			

	}});

}

</script>

<div id="big_box" align="center" >

 <form name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'agent', 'action'=>'update','agentId'=>$this->agentId), 'default', true)?>" method="post">      

 <table width="100%" border="0" cellspacing="5" cellpadding="0" class="frmtable">

  <tr>

  <td width="21%" align="left" valign="top">Choose Branch:<span class="errormsg">*</span></td>

  <td width="79%" align="left" valign="top"><?php echo $this->Form->branch_Id?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Choose Agent:<span class="errormsg">*</span></td>

  <td align="left" valign="top" id="EmployeeIdDiv"><?php echo $this->Form->agent?></td>

  </tr>

  <tr>

  <td align="left" valign="top">First Name:<span class="errormsg">*</span></td>

  <td align="left" valign="top"><?php echo $this->Form->first_name?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Last Name:</td>

  <td align="left" valign="top"><?php echo $this->Form->last_name?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Father Name:</td>

  <td align="left" valign="top"><?php echo $this->Form->father_name?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Husband Name:</td>

  <td align="left" valign="top"><?php echo $this->Form->husbandname?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Email Address:</td>

  <td align="left" valign="top"><?php echo $this->Form->email_address?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Phone Number:<span class="errormsg">*</span></td>

  <td align="left" valign="top"><?php echo $this->Form->phone_number?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Mobile Number:<span class="errormsg">*</span></td>

  <td align="left" valign="top"><?php echo $this->Form->mobile_number?></td>

  </tr>

  <tr>

  <td align="left" valign="top">State:<span class="errormsg">*</span></td>

  <td align="left" valign="top"><?php echo $this->Form->state_id?></td>

  </tr>

  <tr>

  <td align="left" valign="top">City:<span class="errormsg">*</span></td>

  <td align="left" valign="top" id="CityIdDiv"><?php echo $this->Form->city_id?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Address:<span class="errormsg">*</span></td>

  <td align="left" valign="top"><?php echo $this->Form->address?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Date of Birth:</td>

  <td align="left" valign="top"><?php echo $this->Form->date_of_birth?>&nbsp;<img src="<?=APPLICATION_URL?>images/Cal.gif" name="cmdbusinessunit" align="absmiddle" id="cmdbusinessunit" onclick="return displayCalendar(document.myform.date_of_birth,'dd-mm-yyyy',this)"/></td>

  </tr>

  <tr>

  <td align="left" valign="top">Date of Apply:</td>

  <td align="left" valign="top"><?php echo $this->Form->date_of_apply?>&nbsp;<img src="<?=APPLICATION_URL?>images/Cal.gif" name="cmdbusinessunit" align="absmiddle" id="cmdbusinessunit" onclick="return displayCalendar(document.myform.date_of_apply,'dd-mm-yyyy',this)"/></td>

  </tr>

  <tr>

  <td align="left" valign="top">Quallification:</td>

  <td align="left" valign="top"><?php echo $this->Form->quallification?></td>

  </tr>    

  <tr>

  <td align="left" valign="top">Proffession:</td>

  <td align="left" valign="top"><?php echo $this->Form->proffession?></td>

  </tr>

  <tr>

  <td align="left" valign="top">PAN Card Number:</td>

  <td align="left" valign="top"><?php echo $this->Form->pan_card_number?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Amount Deposited:</td>

  <td align="left" valign="top"><?php echo $this->Form->amount_deposit?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Username:</td>

  <td align="left" valign="top"><?php echo $this->Form->username?></td>

  </tr>

  <tr>

  <td align="left" valign="top">Change Password:</td>

  <td align="left" valign="top"><input type="checkbox" value="1" name="ChangePass" id="ChangePass" onclick="showPassword(this);" />

  	<table width="100%" cellpadding="0" cellspacing="0" id="ChangePassword" style="display:none;border: solid 0px #ff0000;">

	<tr>

	<td width="43%" align="left" valign="top" style="border: solid 0px #ff0000;">Password:</td>

	<td width="57%" align="left" valign="top" style="border: solid 0px #ff0000;"><?php echo $this->Form->user_password?></td>

	</tr>

	<tr>

	<td align="left" valign="top" style="border: solid 0px #ff0000;">Confirm Password:</td>

	<td align="left" valign="top" style="border: solid 0px #ff0000;"><?php echo $this->Form->user_confirm_password?></td>

	</tr> 

	</table>

  </td>

  </tr>

  <tr>

  <td align="left" valign="top" style="font-size:11px;"><span class="errormsg">*</span> Required fields</td>

  <td align="left" valign="top"><input type="submit" name="mySubmit" id="mySubmit" value="Submit" /></td>

  </tr>  

</table>

</form>

</div>

<?

if(isset($_REQUEST['ChangePass']))

{

?>

<script language="javascript">

document.getElementById('ChangePass').checked=true;

document.getElementById('ChangePassword').style.display="block";

</script>

<?

}

?>