<?
global $mySession;
$db = new Db();
	$footer_links = $this->Footer_Data;
?>
<script type="text/javascript" language="javascript">
	$(document).ready(function() {
		$('li#<?=$footer_links['page_id']?>').addClass('active');
		});
	
</script>
<div class="container static_page">
        	<h1 class="title"><?=$footer_links['title']?></h1>
        	<div class="content_left">
           	  	<div class="page_content">
                    <p><?=$footer_links['content']?></p>
               
              </div>
          	</div>
            
            
            <div class="content_right">
            
            	<div class="block page_link">
                    <ul>
                    <li id="" class="">
                    <a href="<? echo APPLICATION_URL?>index/testimonials">Testimonials</a>
                    </li>
                    <? 	global $mySessionFront; 
						 $db=new Db();
						 
						$Footer_Data= $db->runQuery ("SELECT * FROM tbl_static_page_detail where status='1'");
						if(is_array($Footer_Data) && count($Footer_Data) > 0) 
                            {
								$i=1;
                            foreach($Footer_Data as $res)
                                {
					?>
                    	<li id="<?=$res['page_id']?>"><a href="<? echo APPLICATION_URL.'Cmspage/index/page_id/'.$res['page_id']?>"><?=$res['title']?></a></li>
                        <? } } ?>
                        <!--<li><a href="#">Testimonials</a></li>
                        <li><a href="#">Help</a></li>
                        <li class="active"><a href="#">Privacy Policies</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Company Blog</a></li>-->
                    </ul>
                </div>
            </div>
            
            
            <div class="clr"></div>
        </div>

					