<?php 
global $mySessionFront;
$db=new Db();

$user_summery=$this->user_id;
?>


<script language = "Javascript">
function summeryedit(){
	//alert('Hello...');
	var user_id=$("#user_id").val();
	//alert(user_id);
	
	var editor1=$("#editor1").val();
	//alert(editor1);
	
	document.getElementById('pro_summary').innerHTML="<img src='<?=IMAGES_URL?>load.gif' border='0'>";
	$.ajax({ url: "<?php echo $this->url(array('controller'=>'dashboard','action'=>'usersummaryedit'),'default',false);?>",
	type: "POST",
	data: ({editor1: editor1}),
		success: function(data){			
		$("#pro_summary").html(data);			
		}
	});
//alert('hello');    baseinfo
}
</script>
<script>
$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
        $('li#mypro').addClass('active');
        });	 


$(document).ready(function() {
		$('textarea#editor1').addClass('ckeditor');
        });	
		
</script>



<div class="container company_profile">
<?php $res=$this->Company_Data; ?>
        	<div class="content_full">
            	<div class="job_head">
                	<div class="img"><img width="124" height="118" src="<?=ADMIN_USR_IMG?><?php echo $res['user_image']?>" alt=""></div>
                    <div class="info">
                    	<h1 class="title captl"><?php echo $res['user_company']?></h1>
                        <div class="manage_profile"><a href="<?=BASE_PATH?>dashboard/companyedit/user_id/<?=$mySessionFront->user['FrontUserId']?>">Manage Profile</a></div>
                        <p class="font12"><?php echo $res['user_city']?>, <?php echo $res['country_name']?></p>
                        <p class="job_title"><span class="blue"><?php echo $res['category_title']?></span></p>
                        <div class="floatleft"><a href="<?=APPLICATION_URL?>subscription/index" class="blue">Add more Credits</a></div>
                        <div class="floatright"><a href="<?=APPLICATION_URL?>job/postjob" class="blue">Post New Job</a></div>
                    </div>
                    <div class="clr"></div>
                </div>
                <div class="list">
                	<div class="block2">
                    	<div class="block2_head">
                        	<h2 class="floatleft">Overview</h2>
                        	<!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                            <div class="clr"></div>
                        </div>
                        <div class="block2_content">
                            <p><!--We live with your dream to Create, inspire and Transform your Digital Identities into an emerging BRAND. We’re an Independent digital design, development and branding agency who strives to provide a better solution to all your business needs.-->
                            <?php echo $res['user_company_detail']?>
                            </p>
                            <ul class="list_3 font12">
                            	<li>
                                	<p class="blue upprcase">INDUSTRIES</p>
                                     <p><?php echo $res['category_title']?></p>
                                </li>
                                <li>
                                	<p class="blue upprcase">ANNUAL REVENUE</p>
                                    <p>$<?php echo $res['user_annual_revenue']?></p>
                                </li>
                                <li>
                                	<p class="blue upprcase">NUMBER OF EMPLOYEES</p>
                                    <p><?php echo $res['user_number_of_employees']?></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="tab_block">
                    	<ul class="tabs">
                        	<li id="manage_ac" ><a href="<?=BASE_PATH?>dashboard/companyedit/user_id/<?=$mySessionFront->user['FrontUserId']?>">Manage Account</a></li>
                            <li id="my_credit" class="active"><a href="<?=BASE_PATH?>dashboard/mycredits" >My Credits</a></li>
                            <li id="pay_his"><a href="<?=BASE_PATH?>dashboard/paymenthistory" >Payment History</a></li>
                            <li id="pay_mthd"><a href="<?=BASE_PATH?>dashboard/paymentmethod" >Payment Method</a></li>
                        </ul>
                        <div class="tab_content company_credit">
                        	<div class="floatleft w48 font12">
                            	<p><strong>Job Posting</strong></p>
                                
                                <table width="100%" cellspacing="0" cellpadding="0" border="0">
                                  <tbody><tr class="head">
                                    <td>Type</td>
                                    <td>Available Quantity</td>
                                    <td>Expiration Date</td>
                                  </tr>
									<?php 
                                        $i=1;
                                        foreach($this->Job_Plan_Data as $My_Job_Plan) {
                                    ?>
                                  <tr>
                                    <td>Normal Job posting</td>
                                    <td>
										<?php 
										if($My_Job_Plan['user_jobs_available']=='0')
										{
										?>
											 N/A
										<?php }else{ 
											echo $My_Job_Plan['user_jobs_available'];
										 }?>
										<? //echo $My_Job_Plan['user_jobs_available']?>
                                    </td>
                                    <td>
									<?php 
										if($My_Job_Plan['user_jobs_expire_on']=='0000-00-00')
										{
										?>
											 N/A
										<?php }else{ 
											echo date("d M Y", strtotime($My_Job_Plan['user_jobs_expire_on']));
										 }?>
									<?php //echo date("d M Y", strtotime($My_Job_Plan['user_job_posting_membership_taken_on']))?></td>
                                  </tr>
                                  <tr>
                                    <td>Prefered Job posting</td>
                                    <td>
										<?php 
										if($My_Job_Plan['user_featured_jobs_available']=='0')
										{
										?>
											 N/A
										<?php }else{ 
											echo $My_Job_Plan['user_featured_jobs_available'];
										 }?>
										<? //echo $My_Job_Plan['user_jobs_available']?>
                                    </td>
                                    <td>
									<?php 
										if($My_Job_Plan['user_featured_jobs_expire_on']=='0000-00-00')
										{
										?>
											 N/A
										<?php }else{ 
											echo date("d M Y", strtotime($My_Job_Plan['user_featured_jobs_expire_on']));
										 }?>
									<?php //echo date("d M Y", strtotime($My_Job_Plan['user_job_posting_membership_taken_on']))?></td>
                                  </tr>
                                  <?php } ?>
                                </tbody></table>
                                
                                
                            </div>
                            <div class="floatright w48 font12">
                            	<p><strong>CV Search balance</strong></p>
                                <table width="100%" cellspacing="0" cellpadding="0" border="0">
                                  <tbody><tr class="head">
                                    <td>Type</td>
                                    <td>Start Date </td>
                                    <td>Expiration Date</td>
                                  </tr>
                                  <?php 
                                        $i=1;
                                        foreach($this->Job_Plan_Data as $My_CV_Plan) {
                                    ?>
                                  <tr>
                                    <td>CV search</td>
                                    <td>
                                    	<?php 
										if($My_CV_Plan['user_resume_membership_taken_on']=='0000-00-00')
										{
										?>
											 N/A
										<?php }else{ 
											echo date("d M Y", strtotime($My_CV_Plan['user_resume_membership_taken_on']));
										 }?>
										<?php //echo date("d M Y", strtotime($My_CV_Plan['user_resume_membership_taken_on']))?>
                                    </td>
                                    <td>
										<?php if($My_CV_Plan['user_resume_membership_expires_on']=='0000-00-00')
										{
										?>
											 N/A
										<?php }else{ 
											echo date("d M Y", strtotime($My_CV_Plan['user_resume_membership_expires_on']));
										 }?>
									<?php //echo date("d M Y", strtotime($My_CV_Plan['user_resume_membership_expires_on']))?>
                                    
                                    </td>
                                  </tr>
                                  <?php } ?>
                                </tbody></table>
                            </div>
                            <div class="clr"></div>
                        </div>
                        
                    </div>
                    <div class="clr"></div>
                </div>
            </div>
            <div class="clr"></div>
        </div>

