<?php 
global $mySessionFront;
$db=new Db();
?>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="<?=JS_URL?>jquery.form.js" type="text/javascript"></script>

<link rel="stylesheet" type="text/css" href="<?=CSS_URL?>jqtransform.css" />
<script type="text/javascript" src="<?=JS_URL?>jquery.jqtransform.js"></script>
<script type="text/javascript" src="<?=JS_URL?>public.js"></script>






	<?php 
//=====================================Job Seeker =====================================
		$res=$this->Job_Seeker_Data;
		//$User_Exp_User_Exp_Activ=$this->User_Exp_User_Exp_Activ;
//===================================== Employee =====================================
	?>
	<div id="main">
    	<div class="container job_apply">
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->



<!--======================================== Uploading CV Forms vai Ajax ===================================-->
            <div class="content_left" id="edit_user_data">
            	<div class="profile_head">
                	<div class="img">
                    <?php 
						if($res['user_image']=='')
						{
						?>
							<img width="167" height="167"  src="<?=IMAGES_URL?>no-avator.png" >
                        <?php }else{ ?>
							<img width="167" height="167" src="<?=ADMIN_IMG?>user_pic/<?php echo $res['user_image']?>" alt="">
						<? }?>
                    </div>
                    
                    <div class="info">
                    	<h1 class="title captl"><? echo $res['user_fname'].' '.$res['user_lname']?></h1>
                    <?
                    	$Credit_Qry="SELECT * FROM tbl_users where user_id ='".$mySessionFront->user['FrontUserId']."'";
						//prd($Credit_Qry);
						$Job_Credit_Result=$db->runQuery($Credit_Qry);
						
						$User_Exp_Activ= "SELECT * FROM tbl_user_experience WHERE is_current ='1' and user_id = '".$mySessionFront->user['FrontUserId']."'";
						$User_Exp_User_Exp_Activ_Data = $db->runQuery($User_Exp_Activ);
					?>   
<h3><?php echo @$User_Exp_User_Exp_Activ_Data[0]['position']?> at <?php echo @$User_Exp_User_Exp_Activ_Data[0]['company']?></h3>
                       
                        
                        <p class="font12 exp_edu1"><?php echo $res['user_city']?>, <?php echo $res['country_name']?> <span>|</span> <!--Information Technologies and Services--><?php echo $res['category_title']?></p>
                        <ul class="exp_edu font12">
                        	<li><span>Current</span> <?php echo @$User_Exp_User_Exp_Activ_Data[0]['company']?></li>
                        </ul>
                    </div>
                    <div class="clr"></div>
                </div>
                
                <div class="profiel_list">
                
                	
<!--========================= User Profile ==========================-->
                    <div class="block1">
                    	<h2 class="floatleft title">Profile Summery</h2>
                        <!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                        <div class="clr"></div>

                        <div class="block1_content">
                        	<?php echo $res['user_profile_summary']?>
                            <!--<ul class="bullet1">
                            	<li>AAA</li>
                            </ul>-->
                        </div>
                    </div>
<!--========================= End of User Profile ==========================-->


<!--========================= Experience ==========================-->
                    
                        
                       <div class="block1" id="experience">
    <h2 class="floatleft title">Experience</h2>
    <div class="floatright">
<a href="javascript:void(0)" onclick="getajax('<?=BASE_PATH?>dashboard/addexperience','experience');" class="floatright edit_btn2" >Add New</a>
    </div>
    <div class="clr"></div>
    <div class="block1_content">
        <ul class="bullet2">
            <?php 
                $i=1;
                foreach($this->User_Exp_All_Val as $User_Multi_Experience) {
            ?>
            <li>
                <div class="number"><?=@$i++;?></div>
                <div class="" style="float:right;">
<!--<a href="#" class="edit_btn2">Edit</a>-->
<a href="javascript:void(0)" onclick="getajax('<?=BASE_PATH?>dashboard/experience/id/<?=@$User_Multi_Experience['id']?>','experience');" class="edit_btn2" >Edit</a>
        </div>
                <div class="info">
                    <h2><?php echo @$User_Multi_Experience['position']?></h2>
                    <h3><?php echo @$User_Multi_Experience['company']?></h3>
                    <p class="font12"><?php echo @$User_Multi_Experience['location']?> <span class="pipe_space">|</span> 
                    <?php echo @$User_Multi_Experience['employment_period_from']?> &ndash; <?php echo $User_Multi_Experience['employment_period_to']?></p>
                    <h4>Job Responsibilities</h4>
                    <p class="font12"><?php echo @$User_Multi_Experience['responsibility']?></p>
                </div>
                <? 
            $Company_Logo_Qry = "select user_image from tbl_users where user_company='".$User_Multi_Experience['company']."'";
            //prd($Company_Logo_Qry);
            $Company_Logo_Qry_Data=$db->runQuery("$Company_Logo_Qry");
            //prd($Company_Logo_Qry_Data); //user_company
            foreach($Company_Logo_Qry_Data as $Company_Logo)
            {	
       ?>
                <div class="img">
                	<img width="112" height="70" src="<?=ADMIN_IMG?>user_pic/<?php echo @$Company_Logo['user_image']?>" alt="">
                </div>
                <div class="clr"></div>
                <?php } ?>
            </li>
            <?php } ?>
        </ul>
    </div>
</div> 
<!--========================= End of Experience ==========================-->


                    <div class="block1">
                    	<h2 class="floatleft title">Skills &amp; Expertise</h2>
                        <!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<p class="font16"><?php echo $res['user_skills_n_expertise']?></p>
                        </div>
                    </div>
                    
                    <!--<div class="block1">-->
                    <div class="block1" id="education">
                    	<h2 class="floatleft title">Education</h2>
<a href="javascript:void(0)" onclick="getajax('<?=BASE_PATH?>dashboard/addeducation','education');" class="floatright edit_btn2" >Add New</a>
                        <!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="bullet2">
                            	<?php 
									$i=1;
									foreach($this->Education_Dashboard as $User_Education) {
								?>
                                <li><div class="" style="float:right;">
                               <!-- <a href="#" class="edit_btn2">Edit</a>-->
<a href="javascript:void(0)" onclick="getajax('<?=BASE_PATH?>dashboard/education/id/<?=$User_Education['id']?>','education');" class="edit_btn2" >Edit</a>
                                </div>
                                	<div class="number"><?=$i++;?></div>
                                    
                                    <div class="info1">
                                    	<h2><?php echo $User_Education['university']?></h2>
                                        <h3><?php echo $User_Education['education_title']?></h3>
                                 <p class="font12">From<?php echo $User_Education['starting_year']?> to <?php echo $User_Education['finishing_year']?></p>
                                	 <?php 
										if($User_Education['is_heighest']=='1')
										{
									?>
									<p class="font12">Is Heighest  <b><?php echo 'Yes';?></b></p>
                       				 <?php }else{ ?>
										<p class="font12">Is Heighest  <b><?php echo 'No';?></b></p>
									<? }?>
                                 
                                    </div>
                                    
                                    <div class="clr"></div>
                                </li>
                                <? } ?> 
                            </ul>
                        </div>
                    </div>
                    
                    <div class="block1">
                    	<h2 class="floatleft title">Personal Information</h2>
                        <!--<div class="floatright"><a href="#" class="edit_btn2">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="view_list">
                            	<li>
                                	<div class="label">Date of Birth</div>
                                    <div class="info"><?php echo date("d M Y", strtotime($res['user_dob']))?></div>
                                </li>
                                <li>
                                	<div class="label">Marital Status</div>
                                    <div class="info"><?php echo $res['user_marital_status']?></div>
                                </li>
                                <li>
                                	<div class="label">Email Address</div>
                                    <div class="info"><?php echo $res['user_email']?></div>
                                </li>
                                <li>
                                	<div class="label">Phone Number</div>
                                    <div class="info"><?php echo $res['user_phone']?></div>
                                </li>
                                <li>
                                	<div class="label">Gender</div>
                                    <div class="info"><?php echo $res['user_gender']?></div>
                                </li>
                                <li>
                                	<div class="label">Nationality</div>
                                    <div class="info"><?php echo $res['nation_title']?></div>
                                </li>
                                <li>
                                	<div class="label">Career Level</div>
                                    <div class="info"><?php echo $res['career_level_title']?></div>
                                </li>
                            </ul>
                            <div class="clr"></div>
                        </div>
                    </div>
                    
                </div>
            </div>
<!--========================================== End Side Bar Job Seeker =========================================-->
           
            <div class="clr"></div>
        </div>		
	</div>

