<?php 
global $mySessionFront;
$db=new Db();

if($mySessionFront->user['userRole']=='Job Seeker') { 
		$res=$this->Skill_Data;
?>
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->
<h2 class="floatleft title">Skills &amp; Expertise</h2>
    <div class="floatright">
<a onclick="getajax('<?=BASE_PATH?>dashboard/skills/user_id/<?=$mySessionFront->user['FrontUserId']?>','skills');" href="#" class="edit_btn2" >Edit</a>                        </div>
    <div class="clr"></div>
    <div class="block1_content">
        <p class="font16"><?php echo $res['user_skills_n_expertise']?> </p>
    </div>
   <? 
		//echo "Hello Job Seeker";
	} else { 
	
	?>
    <div class="floatright">
<a onclick="getajax('<?=BASE_PATH?>dashboard/skills/user_id/<?=$mySessionFront->user['FrontUserId']?>','skills');" href="#" class="edit_btn2" >Edit</a>                        </div>
    <div class="clr"></div>
    <div class="block1_content">
        <p class="font16"><?php echo $res['user_skills_n_expertise']?> </p>
    </div>

	
	<? } ?>
  
 

