<?php global $mySessionFront;?>

<!--============================================ Java Script & Css ===========================================-->	
<script type="text/javascript" language="javascript">
	//$(document).ready(function() {
         // $('body').addClass('home');
        //});
		
	$(document).ready(function() {
        $('li').removeClass('active');
        });	
	
</script>
   
<div class="container static_page">
        	<h1 class="title">terms of use</h1>
        	<div class="content_left">
           	  	<div class="page_content">
                    <div class="testimonials_list">
                    	<div class="block1 font12">
                        	<div class="img"><img width="100" alt="" src="images/company_logo2.jpg"></div>
                            <div class="info">
                            	<p><strong>Standard Chartered Bank</strong>, United Arab Emirates</p>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s make a type specimen book. </p>
                                <p><strong>Ekta Khatri, Emiratisation Officer</strong></p>
                            </div>
                        </div>
                        <div class="block1 font12">
                        	<div class="img"><img width="100" alt="" src="images/company_logo2.jpg"></div>
                            <div class="info">
                            	<p><strong>Standard Chartered Bank</strong>, United Arab Emirates</p>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s make a type specimen book. </p>
                                <p><strong>Ekta Khatri, Emiratisation Officer</strong></p>
                            </div>
                        </div>
                        <div class="block1 font12">
                        	<div class="img"><img width="100" alt="" src="images/company_logo2.jpg"></div>
                            <div class="info">
                            	<p><strong>Standard Chartered Bank</strong>, United Arab Emirates</p>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s make a type specimen book. </p>
                                <p><strong>Ekta Khatri, Emiratisation Officer</strong></p>
                            </div>
                        </div>
                        <div class="block1 font12">
                        	<div class="img"><img width="100" alt="" src="images/company_logo2.jpg"></div>
                            <div class="info">
                            	<p><strong>Standard Chartered Bank</strong>, United Arab Emirates</p>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s make a type specimen book. </p>
                                <p><strong>Ekta Khatri, Emiratisation Officer</strong></p>
                            </div>
                        </div>
                        <div class="clr"></div>
                    </div>
              </div>
          	</div>
            <div class="content_right">
            	<div class="block page_link">
                    <ul>
                    	<li><a href="#">About Us</a></li>
                        <li class="active"><a href="#">Testimonials</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Privacy Policies</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Company Blog</a></li>
                    </ul>
                </div>
            </div>
            <div class="clr"></div>
        </div>