<?
global $mySessionFront;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php	
	if($this->pagetitle==''){
		$pgt  = 'Job Portal | Welcome';
	} else {
		$pgt = $this->pagetitle;
	}
	$cnname = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$actname = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<head>
	<script>var APPLICATION_URL = '<? echo APPLICATION_URL?>';</script>
<title><?php echo $pgt;?></title>
<!--============================================ Java Script & Css ===========================================-->	
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> 
<link rel="stylesheet" type="text/css" href="<? echo CSS_URL?>main.css"/>

 <script type="text/javascript" language="javascript">
 	function msgDiv() {
   		document.getElementById('divError').style.display = "block";
	}
</script>


<script language="javascript">var calImagesPath='<?=APPLICATION_URL?>'</script>
<!--============================================ Java Script & Css ===========================================-->
<script src="<?=JS_URL?>jquery-1.5.js" type="text/javascript"></script>

<!--<script src="<?=JS_URL?>jquery-1.5.js" type="text/javascript"></script>-->

<script language="javascript" type="text/javascript" src="<?=FCK?>ckeditor.js"></script>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

<script src="<?=JS_URL?>jquery.form.js" type="text/javascript"></script>

<script>
	   //getajax('url','','pro_edit');
function getajax(urlval,elm_id)
{	
	//params = param.replace("?","");
	document.getElementById(elm_id).innerHTML="<img src='<?=IMAGES_URL?>load.gif' border='0'>";
		
		$.ajax({ url: urlval,
		type: "POST",
		data: urlval,
		success: function(data){			
			$("#"+elm_id).html(data);			
			}
		});
	
	//jQuery.ajax({ url: urlval,
//				type: "GET",
//				data : urlval,
//				success: function(data){			
//					jQuery("#"+elm_id).html(data);
//				}
//				
//			  });
		
}



<!--============================================ Java Script & Css ===========================================-->
</head>
	<body class="page">
<!--============================================ Start Header ===========================================-->
<header>
  <?php include "header.phtml"; ?>
</header>
<!--============================================ End Header ===========================================-->

<!--============================================ Start Container ===========================================-->        
<?php echo $this->layout()->content; ?>  
<!--============================================ End Container ===========================================-->
            
<!--============================================ Start Footer ===========================================-->
<footer>
<?php include "footer.phtml"; ?>        	
</footer>
<!--============================================ End Footer ===========================================-->
	</body>
</html>
