<?
global $mySession;
$myControllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$myActionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$VisitorLinks = array('staticpages','faq','contactus','login');

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" >
<?php	
	if($this->pagetitle==''){
		$pgt  = 'Amardeep Buildhome ltd.';
	} else {
		$pgt = $this->pagetitle;
	}
	$cnname = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$actname = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<head>
	<script>var APPLICATION_URL = '<? echo APPLICATION_URL?>';</script>

	<?php /*?><script language="javascript" src="<? echo JS_URL?>main.js"></script><?php */?>
<title><?php echo $pgt;?></title>
<!--============================================ Java Script & Css ===========================================-->	
<link rel="stylesheet" type="text/css" href="<? echo CSS_URL1?>style.css"/>
<link rel="stylesheet" type="text/css" href="<? echo CSS_URL1?>extra.css"/>

<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300italic,300,400italic,600,600italic,700,800,800italic' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="<?=JS_URL1?>jquery-1.8.0.min.js" ></script>
<script type="text/javascript" src="<?=JS_URL1?>image_slide.js" ></script>
<script type="text/javascript" src="<?=JS_URL1?>ajax.js" ></script>
<script type="text/javascript" src="<?=JS_URL1?>custom.js" ></script>
<script type="text/javascript" src="<?=JS_URL1?>jquery.carouFredSel-6.2.1-packed.js" ></script>

<!-- fire plugin onDocumentReady -->
<script language="javascript">
	$(function() {
	   $('#foo2').carouFredSel({
			auto: false,
			prev: '#prev2',
			next: '#next2',
			pagination: "#pager2",
			mousewheel: true,
			swipe: {
				onMouse: true,
				onTouch: true
			}
		});
});
</script>		
<!--<script type="text/javascript" src="http://localhost/sybite/jobportal_cake/js/js_files/front/home.js"></script>	-->
<script src="<?=JS_URL?>home.js" type="text/javascript"></script>
<!--============================================ Java Script & Css ===========================================-->
<script language="javascript">
var calImagesPath='<?=APPLICATION_URL?>'
</script>
<script language="javascript">
function checknumber(e)
{
	evt=e || window.event;
	var keypressed=evt.which || evt.keyCode;
	//alert(keypressed);
	if(keypressed!="48" &&  keypressed!="49" && keypressed!="50" && keypressed!="51" && keypressed!="52" 
		&& keypressed!="53" && keypressed!="54" && keypressed!="55" && keypressed!="8" && keypressed!="56" 
		&& keypressed!="57" && keypressed!="45" && keypressed!="46" && keypressed!="37" && keypressed!="39" 
		&& keypressed!="9")
	{
		return false;
	}
}
function checknumbercomma(e)
{
	evt=e || window.event;
	var keypressed=evt.which || evt.keyCode;
	//alert(keypressed);
	if( keypressed!="44" && keypressed!="48" &&  keypressed!="49" && keypressed!="50" && keypressed!="51" && keypressed!="52" 
		&& keypressed!="53" && keypressed!="54" && keypressed!="55" && keypressed!="8" && keypressed!="56" 
		&& keypressed!="57" && keypressed!="46" && keypressed!="37" && keypressed!="39" 
		&& keypressed!="9")
	{
		return false;
	}
}

</script>
</head>
<body>
<div style="background:url(<?=IMAGES_URL?>bg_main.png); background-repeat:repeat-x">
<table width="1000" cellpadding="0" cellspacing="0" border="0" align="center">
  <tr>
    <td align="center" valign="top">
	<table width="100%" cellpadding="0" cellspacing="0" align="center">
      <tr>
        <td align="center" valign="top"><?php include "header.phtml"; ?></td>
      </tr>     
      <tr>
        <td align="center" valign="top" height="" style="background-repeat:repeat;">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td style="background:url(<?=IMAGES_URL?>main_left1.png); background-repeat:repeat-y" width="5"><img src="<?=IMAGES_URL?>blank.gif" width="5" /></td>
			<td style="padding:0 3px; ">
			<?php
				if(isset($this->pagetitle) && !empty($this->pagetitle)) { ?>
				<div id="page_heading"><?php echo $this->pagetitle; ?></div>
			<?php } ?>
		<?php global $mySession;?>
		<div id="errorDiv" style="padding-bottom:5px;">
			<?php  
				if(isset($mySession->errorMsg)){ 
					echo errorMsg($mySession->errorMsg);
					unset($mySession->errorMsg); 
				} 
				if(isset($mySession->sucMsg)){ 
					echo sucessMsg($mySession->sucMsg);
					unset($mySession->sucMsg); 
				} 
				if(isset($mySession->warningMsg)){ 
					echo warningMsg($mySession->warningMsg);
					unset($mySession->warningMsg); 
				}
			?>
		</div>
		<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center">
          <tr>
            <td align="center" valign="top"><div align="center">
			<?php if($cnname=='index' && $actname=='index') {  } else { ?><div id="innerdiv"><?php } ?>
			
			<?php echo $this->layout()->content; ?>
			<?php if($cnname=='index' && $actname=='index') {  } else { ?><br />
<br />
<br />
<br />
<br />
</div><?php } ?>
			<br />
<br />
<br />
<br />
<br />

			</div>
			</td>              
	      </tr>
        </table>
		<br />
<br />
<br />
<br />
</td>
			<td style="background:url(<?=IMAGES_URL?>main_right1.png); background-repeat:repeat-y" width="11"><img src="<?=IMAGES_URL?>blank.gif" width="11" /></td>
		  </tr>
		  
		  

		
		<tr>
			<td style="background:url(<?=IMAGES_URL?>main_left2.png); background-repeat:no-repeat" width="5"><img src="<?=IMAGES_URL?>blank.gif" width="5" /></td>
			<td style="background:url(<?=IMAGES_URL?>main_center.png); background-repeat:repeat-x" ><img src="<?=IMAGES_URL?>main_center1.png" width="7"  /></td>
			<td style="background:url(<?=IMAGES_URL?>main_right2.png); background-repeat:no-repeat" width="11"><img src="<?=IMAGES_URL?>blank.gif" width="11" /></td>
		  </tr>
		</table></td>
      </tr>
      <tr>
        <td align="left" valign="top"><?php include "footer.phtml"; ?></td>
      </tr>
    </table></td>
  </tr>
</table>
</div>
</body>
</html>