<?php 
global $mySessionFront;
$db=new Db();
?>

<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
				$('#paging_container1').pajinate();
			});
</script>
<script type="text/javascript" language="javascript">
	$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
        $('li#mypro').addClass('active');
        });	 
		  
</script>
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->

<div class="container job_apply">
        	<div class="content_left">
            <?php 
				$res=$this->Job_Seeker_Data;			
			?>
            	<div class="profile_head">
                	<div class="img">
                    <?php 
						if($res['user_image']=='')
						{
						?>
							<img width="167" height="167"  src="<?=IMAGES_URL?>no-avator.png" >
                        <?php }else{ ?>
							<img width="167" height="167" src="<?=ADMIN_IMG?>user_pic/<?php echo $res['user_image']?>" alt="">
						<? }?>
                    </div>
                    
                    <div class="info">
                    	<h1 class="title captl"><? echo $res['user_fname'].' '.$res['user_lname']?></h1>
                    <?
                    	$Credit_Qry="SELECT * FROM tbl_users where user_id ='".$mySessionFront->user['FrontUserId']."'";
						//prd($Credit_Qry);
						$Job_Credit_Result=$db->runQuery($Credit_Qry);
						
						$User_Exp_Activ= "SELECT * FROM tbl_user_experience WHERE is_current ='1' and user_id = '".$mySessionFront->user['FrontUserId']."'";
						$User_Exp_User_Exp_Activ_Data = $db->runQuery($User_Exp_Activ);
					?>   
<h3><?php echo @$User_Exp_User_Exp_Activ_Data[0]['position']?> at <?php echo @$User_Exp_User_Exp_Activ_Data[0]['company']?></h3>
                       
                        
                        <p class="font12 exp_edu1"><?php echo $res['user_city']?>, <?php echo $res['country_name']?> <span>|</span> <!--Information Technologies and Services--><?php echo $res['category_title']?></p>
                        <ul class="exp_edu font12">
                        	<li><span>Current</span> <?php echo @$User_Exp_User_Exp_Activ_Data[0]['company']?></li>
                        </ul>
                    </div>
                    <div class="clr"></div>
                </div>
             
               <div class="list">
            <h1 class="title captl floatleft">View All Jobs</h1>
            
            	<div class="clr"></div>
            
            
           	<div id="paging_container1">
            <ul class="content">
              
              
              
                 
                 <?  if(is_array($this->AllJob_Details) && count($this->AllJob_Details) > 0) {
					foreach($this->AllJob_Details as $Myjob) { ?>	 
                <li>
                    
                    <div class="list_block ">
                    	<div class="head font12">
                            <div class="floatleft">
<h4><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$Myjob['Job_id']?>" class="black"><?php echo $Myjob['job_title']?></a></h4>
                                <p><?=$Myjob['job_city']?> - <span class="blue"><?=$Myjob['country_name']?></span></p>
                            </div>
                            <div class="floatright">
                            	<p><?php echo date("d-m-Y", strtotime($Myjob['job_posted_on']))?></p>
                                <!--<p class="orng"><strong>Featured Job</strong></p>-->
                            </div>
                        </div>
                        <p class="clr font12"><?=substr($Myjob['job_description'],0,186)?></p>
                        <div class="footer font11">
                        	 <span>Job Role: <strong class="blue"><?=$Myjob['job_role_title']?></strong></span>
                             <span>Company Industry: <strong class="blue"><?=$Myjob['category_title']?></strong></span>
                             <span>Career Level: <strong class="blue"><?=$Myjob['career_level_title']?></strong></span>
                        </div>
                        
                    </div>
                </li>
                 <? } ?>
                 <? } else { ?> 
                <li>
               		<div class="list_block">
                        
                        <div class="footer font11">
                             <h4>No Job Found</h4> 
                        </div>
                    </div>
                </li>
                 <? } ?>
                 
            </ul>
            <div class="page_navigation" style="padding-left:125px;"></div>	
            <!--<div class="paging">
                <ul>
                    <li><a href="#">Prev</a></li>
                    <li><span>1</span></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
            </div>-->
            </div>
        </div>
            </div>
            <div class="content_right">
            	<div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyApply_Job=$this->Apply_Job;
							$MyTotalSave=$this->SaveJobs; 
							$MyTotalNoti=$this->Job_Noti;
						?>
                    <ul>
                    	<li><a href="<?=APPLICATION_URL?>user/jobsapplied"><span class="number number_green"><?php echo $MyApply_Job['TotalApply']?></span>Apply Jobs</a></li>
                         <li><a href="<?=APPLICATION_URL?>user/jobsaved"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
                        <li><a href="<?=APPLICATION_URL?>user/notification"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
                        <li><a href="<?=APPLICATION_URL?>user/alljobs"><span class="number">45</span> Profile Views</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
                <div class="block recommended font12">
                	<h2 class="title">Recommended Jobs</h2>
                    <ul>
						<?php 
                            $i=1;
                            foreach($this->Rec_Job as $MyRec_Job) {
                        ?>
                    	<li>
                        	<div class="img">
                            	<?php 
								if($MyRec_Job['user_image']=='')
								{
								?>
									 <img width="100" height="70"  src="<?=IMAGES_URL?>no-avator.png" >
									
								<?php }else{ ?>
									 <img width="100" height="70" src="<?=ADMIN_IMG?>user_pic/<?php echo $MyRec_Job['user_image']?>" alt="">
								<? }?>
                            </div>
                            <div class="info">
                            	<h3><?php echo $MyRec_Job['job_title']?></h3>
                                <p><strong>Posted by</strong> <?php echo $MyRec_Job['user_company']?> for <?php echo $MyRec_Job['job_city']?></p>
                                <p><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$MyRec_Job['id']?>" class="blue1">View &amp; Apply</a> - <?php echo date("d-m-Y", strtotime($MyRec_Job['job_posted_on']))?></p>
                            </div>
                        </li>
                        <?php } ?>
                        <li class="align-right"><a href="<?=APPLICATION_URL?>job/alljobs" class="black">View All →</a></li>
                    </ul>
                </div>
                
                <?php 
					$i=1;
					foreach($this->Add_Banner_Data as $Add_Banner_List) {
				?>
                <div class="block ad align-center">
                <!--<img alt="" src="images/google_ad1.jpg">	banner_window_open	banner_link	-->
                <!--<a target="_blank" href="http://google.com">-->
                <a target="<?php echo $Add_Banner_List['banner_window_open']?>" href="<?php echo $Add_Banner_List['banner_link']?>">
	                <img width="300" height="268" src="<?=ADMIN_IMG?>banners/<?php echo $Add_Banner_List['banner_image']?>" alt="">
                </a>    
                </div>
                <!--<div class="block ad align-center"><img alt="" src="images/google_ad2.jpg"></div>-->
                <?php }?>
                
            </div>
            <div class="clr"></div>
        </div>

