<?php 
global $mySessionFront;
$db=new Db();

?>
<!--======================================== Auto Suggest vai Jquery ===================================-->
<link rel="stylesheet" href="<?=JS_URL?>jquery-ui.css" />

<script src="<?=JS_URL?>jquery-ui.js"></script>
<!--======================================== Auto Suggest vai Jquery ===================================-->

<link rel="stylesheet" type="text/css" href="<?=CSS_URL?>jqtransform.css" />
<script type="text/javascript" src="<?=JS_URL?>jquery.jqtransform.js"></script>
<script type="text/javascript" src="<?=JS_URL?>public.js"></script>
 
 <script type="text/javascript" language="javascript">
 
	$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
        $('li#myjob').removeClass('active');
        });	 
	
	$(document).ready(function() {
        $('select#sub_cat_id').addClass('selectbox');
        });  
</script>
<script language="javascript">
function getsubcat(CategorySno)
{
	document.getElementById('SubCatDiv').innerHTML="<img src='<?=APPLICATION_URL_ADMIN?>images/load.gif' border='0'>";
	//alert(document.getElementById('SubCatDiv'));
	$.ajax({ url: "<?php echo $this->url(array('controller'=>'job','action'=>'getsubcat'),'default',true);?>",
	type: "POST",
	data: ({CategorySno : CategorySno}),
	success: function(data){			
	$("#SubCatDiv").html(data);			
	}});
}
</script>
<!--======================================== Loading Forms vai Ajax ===================================-->
<div class="container job_post featured_job_post">
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->
        	<div class="content_left">
<?php $res=$this->Company_Data; ?>

            	<div class="job_head">
                	<div class="img">
                    	<img width="124" height="118" src="<?=ADMIN_USR_IMG?><?php echo $res['user_image']?>" alt="">
                    </div>
                    
                    <div class="info">
                    	<h1 class="title captl"><?php echo $res['user_company']?></h1>
                        <p class="font12"><?php echo $res['user_city']?>, <?php echo $res['country_name']?></p>
                        <p class="job_title"><span class="blue"><?php echo $res['category_title']?></span></p>

                        <div class="floatleft"><a href="<?=APPLICATION_URL?>subscription/index" class="black">Add more Credits</a></div>
                        <div class="floatright"><a href="<?=APPLICATION_URL?>job/postjob" class="blue">Post New Job</a></div>
                        
                    </div>
                    <div class="clr"></div>
                </div>
                <div class="form_block">
                	<h1 class="title captl">New Job Posting</h1>
                    <div class="clr"></div>
<form name="" id="" action="" method="post" enctype="multipart/form-data">    
    <!--<div class="ftrd_form selectForm">-->
    <div class="ftrd_form selectForm jqtransformdone">
        <div class="full">
            <div class="label">Job Title</div>
            <div class="field"><? echo $this->myform->Job_Title?></div>
        </div>
        <div class="full">
            <div class="label">Job Key Words</div>
            <div class="field"><? echo $this->myform->job_keywords?></div>
            <div class="padT3">Seperated by comma ( , )</div>
        </div>
        <div class="full">
            <div class="label">Category</div>
            <div class="field field1"><? echo $this->myform->CategorySno?></div>
            
            <div class="label">Sub Category</div>
            <div class="field field1" id="SubCatDiv"><? echo $this->myform->SubCatId?></div>
        </div>
        <div class="full">
            <div class="label">Description</div>
            <div class="field"><? echo $this->myform->Description?></div>
        </div>
        <div class="full">
            <div class="label">Responsibilities</div>
            <div class="field"><? echo $this->myform->Responsibilities?></div>
        </div>
        <div class="full">
            <div class="label">Skills Required</div>
            <div class="field"><? echo $this->myform->Skills_Required?></div>
        </div>
        <div class="full">
            <div class="label">Country</div>
            <div class="field field1"><? echo $this->myform->CountryId?></div>
            <div class="label">City</div>
            <div class="field field1"><? echo $this->myform->City?></div>
        </div>
        <div class="full">
            <div class="label">Employment Type</div>
            <div class="field field1"><? echo $this->myform->Employment_Type?></div>
            <div class="label">Job Type</div>
            <div class="field field1"><? echo $this->myform->Job_Type?></div>
        </div>
        <div class="full">
            <div class="label">Education</div>
            <div class="field field1"><? echo $this->myform->EducationId?></div>
            <div class="label">Experience</div>
            <div class="field field1"><? echo $this->myform->ExperienceId?></div>
        </div>
        <div class="full">
            <div class="label">Career Level</div>
            <div class="field field1"><? echo $this->myform->Career_Level?></div>
            <div class="label">Travel Required</div>
            <div class="field field1"><? echo $this->myform->Travel_Required?></div>
        </div>
	<!--==============================================================================================================================================-->
        <div class="full">
            <div class="label">Relocation</div>
            <div class="field field1"><? echo $this->myform->Relocation?></div>
            <div class="label">Job Role</div>
            <div class="field field1"><? echo $this->myform->job_role?></div>
        </div>
	<!--==============================================================================================================================================-->
    
        <div class="full">
            <div class="label">Email</div>
            <div class="field field1"><? echo $this->myform->Email?></div>
            <div class="label">Phone Number</div>
            <div class="field field1"><? echo $this->myform->Phone_Number?></div>
            
        </div>
        <div class="full">
            <div class="label">Contact  Name</div>
            <div class="field field1"><? echo $this->myform->Contact_Name?></div>
            <div class="label">Fax</div>
            <div class="field field1"><? echo $this->myform->Fax?></div>
        </div>
         <div class="full">
            <div class="label">Sallary</div>
            <div class="field "><? echo $this->myform->Sallary?></div>
        </div>
        <div class="clr"></div>
    </div>                    
    <div class="form_btns form_btns1">
    <input type="hidden" name="credit_available" id="credit_available" value="1" />
    <input type="submit" class="save_job_btn" name="submit" value="Save this Job" ><!-- Job Status Deactiv -->
    <input type="submit" class="post_job_btn" name="submit" value="Post this Job"><!-- Job Status Activ -->
       
	   <? //echo $this->myform->save_job?>
       <? //echo $this->myform->post_job?>
       
        <span class="mdl_text">or</span>  
        <input type="button" class="post_btn" value="post as prefered job" onclick="window.location='<?=BASE_PATH?>job/featuredjobpost'"> 
        
        <!--job/featuredjobpost-->
        <a href="#" class="black underline add_credits_link">Add more credits</a>
    </div>
</form>
                    

                </div>
            </div>

<!--============================================ Side Bar Employee ===========================================-->
			<div class="content_right">
            	<div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyPosted_Job=$this->Emp_Posted_Job;
							$MyTotalSave=$this->Emp_SaveJobs; 
							$MyTotalNoti=$this->Emp_Job_Noti;
							$Resumes_Total=$this->Resumes_Data_Total;
						?>
                    <ul>
   <li><a href="<?=APPLICATION_URL?>company/companypostedjob"><span class="number number_green"><?php echo $MyPosted_Job['TotalApply']?></span>Jobs Posted</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companysavejob"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companymsg"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
   <li><a href="<?=APPLICATION_URL?>company/companyresumes"><span class="number"><?php echo $Resumes_Total['Total_Resumes']?></span> Resumes</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
                <div class="block credit_blnc font12">
                	<h2 class="title">Credit Balance</h2>
                    <div class="in_block1">
                    	<h3>Job Posting Credits</h3>
                        
                        <div class="in_block1_content">
                            <ul class="bullet6 font12">
                                <li>Normal Job Postings: <?php echo $res['user_jobs_available'] ?></li>
                                <li>Premier Job Postings: <?php echo $res['user_featured_jobs_available'] ?></li>
                                <li>(Expire <?php echo date("d-M-Y", strtotime($res['user_jobs_expire_on'])) ?>)</li>
                                <li><a href="<?=APPLICATION_URL?>subscription/jobcredits" class="blue">Add job posting credits</a></li>
                                <li><a href="<?=APPLICATION_URL?>dashboard/mycredits" class="blue">View Credit </a></li>
                                <li><a href="<?=APPLICATION_URL?>dashboard/paymenthistory" class="blue">View Payment History</a></li>
                            </ul>
<!--<p class="align-right"><a href="<?=APPLICATION_URL?>subscription/jobcredits" class="maroon underline">Buy Job Posting Credits</a></p>-->
                        </div>
                    </div>
                    <div class="in_block1">
                        <h3>CV Search Credits</h3>
                        <div class="in_block1_content">                    	
                            <ul class="bullet6 font12">
                                <li>Global Search<br>(Expire <?php echo date("d-M-Y", strtotime($res['user_resume_membership_expires_on'])) ?>)</li>
                                <li><a href="<?=APPLICATION_URL?>subscription/cvcredits" class="blue">Subscribe to CV Search</a></li>
                            </ul>
                        </div>
                    </div>
                    <ul class="bullet6 font12">
                        <li><a href="<?=APPLICATION_URL?>dashboard/paymenthistory" class="blue">View Payment History</a></li>
                        <li><a href="<?=APPLICATION_URL?>dashboard/mycredits" class="blue">View Credit</a></li>
                    </ul>
                </div>
            </div>	
<!--========================================== End Side Bar Employee =========================================-->
            
            <div class="blue_footer">
            	<h2 class="title align-center">Benefits of Featured Jobs</h2>
                <ul class="list_3">
                	<li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>Occupancy.png"></div>
                        <div class="info">
                        	<h4>Occupancy</h4>
                            <p>Don’t ever experience downtime again on your rental property</p>
                        </div>
                    </li>
                    <li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>Exposure.png"></div>
                        <div class="info">
                        	<h4>Exposure</h4>
                            <p>Unlike local agents, our service gives you access to 50+ million travelers to Africa .</p>
                        </div>
                    </li>
                    <li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>Service.png"></div>
                        <div class="info">
                        	<h4>Service</h4>
                            <p>Our additional services make it easy for you to be anywhere and 	rent your place</p>
                        </div>
                    </li>
                    <li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>Make-Money.png"></div>
                        <div class="info">
                        	<h4>Make Money</h4>
                            <p>Let us know your nightly rate, and we make it all happen</p>
                        </div>
                    </li>
                    <li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>Security.png"></div>
                        <div class="info">
                        	<h4>Security</h4>
                            <p>We verify both you and your guests.</p>
                        </div>
                    </li>
                    <li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>Save.png"></div>
                        <div class="info">
                        	<h4>Save</h4>
                            <p>- You don’t have to spend on advertising your property as long as you 	are listed with us.</p>
                        </div>
                    </li>
                    <li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>No-Hidden-Costs.png"></div>
                        <div class="info">
                        	<h4>No Hidden Costs</h4>
                            <p>Let us know your nightly rate, and we make it all happen</p>
                        </div>
                    </li>
                    <li>
                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>Control.png"></div>
                        <div class="info">
                        	<h4>Control </h4>
                            <p>Decide at anytime to change availability</p>
                        </div>
                    </li>
                    <li>

                    	<div class="img"><img alt="" src="<?=IMAGES_URL?>No-Worries.png"></div>
                        <div class="info">
                        	<h4>No Worries </h4>
                            <p>We are here for you 24/7</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="clr"></div>
        </div>	
 

