<?php 
global $mySessionFront;
$db=new Db();

?>

<!--======================================== Auto Suggest vai Jquery ===================================-->

<link rel="stylesheet" href="<?=JS_URL?>jquery-ui.css" />
<script src="<?=JS_URL?>jquery-ui.js"></script>
<script src="<?=JS_URL?>ddaccordion.js"></script>
<script type="text/javascript">


ddaccordion.init({
	headerclass: "submenuheader", //Shared CSS class name of headers group
	contentclass: "submenu", //Shared CSS class name of contents group
	revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click", "clickgo", or "mouseover"
	mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
	collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
	defaultexpanded: [], //index of content(s) open by default [index1, index2, etc] [] denotes no content
	onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
	animatedefault: false, //Should contents open by default be animated into view?
	persiststate: true, //persist state of opened contents within browser session?
	toggleclass: ["", ""], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
	//togglehtml: ["suffix", "<img src='images/drop-down-erro2.jpg' class='statusicon' />", "<img src='images/drop-down-erro.jpg' class='statusicon' />"],
	togglehtml: ["suffix", "", ""],
	 //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
	animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
	oninit:function(headers, expandedindices){ //custom code to run when headers have initalized
		//do nothing
	},
	onopenclose:function(header, index, state, isuseractivated){ //custom code to run whenever a header is opened or closed
		//do nothing
	}
})


</script>
<!--======================================== Auto Suggest vai Jquery ===================================-->

<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>-->
<link rel="stylesheet" type="text/css" href="<?=CSS_URL?>jqtransform.css" />
<script type="text/javascript" src="<?=JS_URL?>jquery.jqtransform.js"></script>
<script type="text/javascript" src="<?=JS_URL?>public.js"></script>
 
 <script type="text/javascript" language="javascript">
 
	$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
        $('li#myjob').addClass('active');
        });	 
		  
</script>
<!--======================================== Loading Forms vai Ajax ===================================-->
<script src="<?=JS_URL?>jquery.moreless.js"></script>
<script type="text/javascript">
	$(function () {
	
		$(document).moreless(
		{
			startHeight: 143,
			moreText: 'More...',
			lessText: 'Less...',
			outerContainer: 'more-less',
			MycontentContainer: 'text-block',
			anchorClass: 'adjust'
		}
	);
	
	});
</script>
<style>
.adjust {
    color: #00A6A4; font-weight:bold; padding-left:150px
}
a {
    color: #00A6A4;
    text-decoration: none;
}
</style>
<script>
	$(function() {
<? 
	foreach($this->Job_Keyword as $akash)
	{
?>
	var availableTags = [<?=$akash['job_key_word']?>];

<? } ?>
	function split( val ) {
	return val.split( /,\s*/ );
	}
	function extractLast( term ) {
	return split( term ).pop();
	}
	$( "#tags" )
	// don't navigate away from the field on tab when selecting an item
	.bind( "keydown", function( event ) {
	if ( event.keyCode === $.ui.keyCode.TAB &&
	$( this ).data( "ui-autocomplete" ).menu.active ) {
	event.preventDefault();
	}
	})
	.autocomplete({
	minLength: 0,
	source: function( request, response ) {
	// delegate back to autocomplete, but extract the last term
	response( $.ui.autocomplete.filter(
	availableTags, extractLast( request.term ) ) );
	},
	focus: function() {
	// prevent value inserted on focus
	return false;
	},
	select: function( event, ui ) {
	var terms = split( this.value );
	// remove the current input
	terms.pop();
	// add the selected item
	terms.push( ui.item.value );
	// add placeholder to get the comma-and-space at the end
	terms.push( "" );
	this.value = terms.join( ", " );
	return false;
	}
	});
	});
</script>
    <?
	$db=new Db();
	$qry="SELECT job_keywords FROM tbl_jobs";
	//prd($qry);
	$job_key_word = $db->runQuery("$qry");
	//prd($job_key_word);
	if(is_array($job_key_word) && count($job_key_word) > 0)
		{
	foreach($job_key_word as $Myjob) {
	//prd($job_key_word=explode(",",$job_key_word[0]['job_keywords']));
		
		//echo $Myjob=explode(",",$job_key_word[0]['job_keywords']); exit;
	} }
?>
<!--class="text-block"-->
	<div class="container search_result">
        	<h1 class="title">Jobs in the Gulf and Middle East <span>We found 5000+ job vacancies for you.</span></h1>
            <div class="content_left">
            
            	<div class="result_bar font12">
                	<div class="floatleft selectForm"><span class="label">Sort by:</span> 
                    	<select><option>Recommended</option></select>
                    </div>
                    <div class="floatright paging">
                    	<ul>
                        	<li><a href="#">&lt;</a></li>
                            <li><span>1</span></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&gt;</a></li>
                        </ul>
                        
                    </div>
                    <div class="clr"></div>
                </div>
               
                <div class="list" id="list">
                <? if(is_array($this->advsearchlist) && count($this->advsearchlist) > 0) {
					foreach($this->advsearchlist as $Myjob) { ?>	
                    
                    <div class="list_block ">
                    	<div class="head font12">
                            <div class="floatleft">
                                <h4><a class="black" href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$Myjob['id']?>"><?=$Myjob['job_title']?></a></h4>
                                <p><?php echo $Myjob['job_city']?> - <span class="blue"><?php echo $Myjob['country_name']?></span></p>
                            </div>
                            <div class="floatright">
                            	<p><?php echo date("d-m-Y", strtotime($Myjob['job_posted_on']))?></p>
                                <!--<p class="orng"><strong>Featured Job</strong></p>-->
                            </div>
                        </div>
                        <p class="clr font12"><?= substr($Myjob['job_description'],0,170)?></p>
                        <div class="footer font11">
                        	 <span>Job Role: <strong class="blue"><?php echo $Myjob['job_role_title']?></strong></span>
                             <span>Company Industry: <strong class="blue"><?php echo $Myjob['category_title']?></strong></span>
                             <span>Career Level: <strong class="blue"><?php echo $Myjob['career_level_title']?></strong></span>
                        </div>
                        
                    </div>
                 <? } ?>
                 <? } else {?> 
                 	<div class="list_block featured_list_block">
                 		<h4>PLEASE REFINE YOUR SEARCH</h4>   
                    </div>
				 <? } ?>  
                    <div class="clr"></div>
                </div>
                
                <div class="result_bar font12">
                    <div class="floatright paging">
                    	<ul>
                        	<li><a href="#">&lt;</a></li>
                            <li><span>1</span></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&gt;</a></li>
                        </ul>
                    </div>
                    <div class="clr"></div>
                </div>
            </div>
            
            
            
			
            <div class="content_right">
              <div class="glossymenu">
                    <div class="block search_block selectForm">
                        <h2 class="submenuheader">Refine your search</h2>
                        <div class="search_form submenu">
                            <p>
                                <input type="text" class="inputbox" value="Search Keywords">
                             </p>
                            <p><select class="selectbox"><option>All</option></select></p>
                            <p class="align-center"><input type="button" value="search NOW" class="search_btn"></p>
                            <p class="font16 align-center"><a class="black" href="#">Advance Search</a></p>
                        </div>
                    </div>
                    <div class="block filter font12">
                        <h2 class="title collapse submenuheader">Job Location</h2>
                         <div class=" filter_content">
                            <ul class="bullet5 text-block submenu">
<?php	
$MyCnty_Qry="SELECT tbl_countries.country_id, tbl_countries.country_name  FROM tbl_countries";
$MyCnty_Data = $db->runQuery($MyCnty_Qry);
foreach($MyCnty_Data as $My_Name)
{ 
$Total_User_Qry= "Select tbl_jobs.job_country, count(job_country) as Total_Cont FROM tbl_jobs  WHERE job_status = '1' and job_country = '".$My_Name['country_id']."' ";
$Total_User_Qry_Data = $db->runQuery($Total_User_Qry);
?>
                            <li>
       <a onclick="getajax('<?=BASE_PATH?>job/countryajax/country_id/<?=$Total_User_Qry_Data[0]['job_country']?>','list');" href="#" >
                                    <?=$My_Name['country_name']?> (<?=$Total_User_Qry_Data[0]['Total_Cont']?>)
                                </a>          
                            </li>
                             <?php } ?>
                           </ul>
                          
                        </div>
                        </div>
                    <div class="block filter font12">
                <h2 class="title collapse submenuheader">Sallary Refinement</h2>
                <div class="filter_content">
                <ul class="bullet5 text-block submenu">
                    <li><a onclick="getajax('<?=BASE_PATH?>job/jobsallaryajax/job_sallary/1000,10000','list');" href="javascript:void(0)" >$ 5000 - 10000</a></li>
                    <li><a onclick="getajax('<?=BASE_PATH?>job/jobsallaryajax/job_sallary/10000,15000','list');" href="javascript:void(0)">$ 10000 - 15000</a></li>
                    <li><a onclick="getajax('<?=BASE_PATH?>job/jobsallaryajax/job_sallary/14000,20000','list');" href="javascript:void(0)">$ 15000 - 20000</a></li>
                    <li><a onclick="getajax('<?=BASE_PATH?>job/jobsallaryajax/job_sallary/20000,25000','list');" href="javascript:void(0)">$ 20000 - 25000</a></li>
                </ul>
                </div>
            </div>
                    <div class="block filter font12">
                        <h2 class="title collapse submenuheader">Job Role</h2>
                        <div class="filter_content">
                        <ul class="bullet5 text-block submenu">
<?php
$MyCnty_Qry="SELECT tbl_job_roles.job_role_id, tbl_job_roles.job_role_title  FROM tbl_job_roles";

$MyCnty_Data = $db->runQuery($MyCnty_Qry);
//prd($MyCnty_Data);
foreach($MyCnty_Data as $My_Name)
{ 

$Total_User_Qry= "Select tbl_jobs.job_role,count(job_role) as Total_Cont FROM tbl_jobs  WHERE job_status = '1' and job_role = '".$My_Name['job_role_id']."' ";
$Total_User_Qry_Data = $db->runQuery($Total_User_Qry);
?>
                                <li>
                <a onclick="getajax('<?=BASE_PATH?>job/jobroleajax/job_role_id/<?=$Total_User_Qry_Data[0]['job_role']?>','list');" href="javascript:void(0)" >
                                    <?=$My_Name['job_role_title']?> (<?=$Total_User_Qry_Data[0]['Total_Cont']?>)
                                </a>
                                </li>
                            <? } ?>
                        </ul>
                        </div>
                    </div>
                    <div class="block filter font12">
                        <h2 class="title collapse submenuheader">Company Industry</h2>
                        <div class="filter_content">
                        <ul class="bullet5 text-block submenu">
<?php
$MyCnty_Qry="SELECT tbl_job_categories.cat_id, tbl_job_categories.category_title  FROM tbl_job_categories";

$MyCnty_Data = $db->runQuery($MyCnty_Qry);
//prd($MyCnty_Data);
foreach($MyCnty_Data as $My_Name)
{ 

$Total_User_Qry= "Select tbl_jobs.job_category, count(job_category) as Total_Cont FROM tbl_jobs  WHERE job_status = '1' and job_category = '".$My_Name['cat_id']."' ";
$Total_User_Qry_Data = $db->runQuery($Total_User_Qry);
?>
                                <li>
<a onclick="getajax('<?=BASE_PATH?>job/companyajax/cat_id/<?=$Total_User_Qry_Data[0]['job_category']?>','list');" href="javascript:void(0)" >
                                   <?=$My_Name['category_title']?> (<?=$Total_User_Qry_Data[0]['Total_Cont']?>)
                                </a>
                                </li>
                            <? } ?>
                        </ul>
                        </div>
                    </div>
                    <div class="block filter font12">
                        <h2 class="title collapse submenuheader">Career Level</h2>
                        <div class="filter_content">
                        <ul class="bullet5 text-block submenu">
<?php
$MyCnty_Qry="SELECT tbl_career_levels.career_level_title, tbl_career_levels.career_level_id  FROM tbl_career_levels";

$MyCnty_Data = $db->runQuery($MyCnty_Qry);
//prd($MyCnty_Data);
foreach($MyCnty_Data as $My_Name)
{ 

$Total_User_Qry= "Select tbl_jobs.job_career_level, count(job_career_level) as Total_Cont FROM tbl_jobs  WHERE job_status = '1' and job_career_level = '".$My_Name['career_level_id']."' ";
$Total_User_Qry_Data = $db->runQuery($Total_User_Qry);
?>
                                <li>
                          <a onclick="getajax('<?=BASE_PATH?>job/careerlevelsajax/career_level_id/<?=$Total_User_Qry_Data[0]['job_career_level']?>','list');" href="javascript:void(0)" >
                                    <?=$My_Name['career_level_title']?> (<?=$Total_User_Qry_Data[0]['Total_Cont']?>)
                                </a>
                                </li>
                            <? } ?>
                        </ul>
                        </div>
                    </div>
 <div class="block filter font12">
    <h2 class="title collapse submenuheader">Date Posted</h2>
  <div class="filter_content">
    <ul class="bullet5 text-block submenu">
        <li><a onclick="getajax('<?=BASE_PATH?>job/jobbydateajax/job_posted_on/now()','','list');" href="javascript:void(0)" >Today</a></li>
        <li><a onclick="getajax('<?=BASE_PATH?>job/jobbydateajax/job_posted_on/2','','list');" href="javascript:void(0)" >Past 2 days</a></li>
        <li><a onclick="getajax('<?=BASE_PATH?>job/jobbydateajax/job_posted_on/7','','list');" href="javascript:void(0)" >Past 7 days</a></li>
        <li><a onclick="getajax('<?=BASE_PATH?>job/jobbydateajax/job_posted_on/21','','list');" href="javascript:void(0)" >Past 21 Days</a></li>
        <li><a onclick="getajax('<?=BASE_PATH?>job/jobbydateajax/job_posted_on/30','','list');" href="javascript:void(0)" >Past 30 Days</a></li>
    </ul>
  </div>
</div>
                    <div class="block filter font12">
                        <h2 class="title collapse submenuheader">Company Type</h2>
                        <div class="filter_content">
                        <ul class="bullet5 text-block submenu">
<?php
$MyCnty_Qry="SELECT tbl_job_sub_categories.sub_cat_id, tbl_job_sub_categories.sub_category_title  FROM tbl_job_sub_categories";

$MyCnty_Data = $db->runQuery($MyCnty_Qry);
//prd($MyCnty_Data);
foreach($MyCnty_Data as $My_Name)
{ 

$Total_User_Qry= "Select tbl_jobs.job_sub_category, count(job_sub_category) as Total_Cont FROM tbl_jobs  WHERE job_status = '1' and job_sub_category = '".$My_Name['sub_cat_id']."' ";
$Total_User_Qry_Data = $db->runQuery($Total_User_Qry);
?>
                                <li>
                          <a onclick="getajax('<?=BASE_PATH?>job/companytypajax/sub_cat_id/<?=$Total_User_Qry_Data[0]['job_sub_category']?>','list');" href="javascript:void(0)" >
                                    <?=$My_Name['sub_category_title']?> (<?=$Total_User_Qry_Data[0]['Total_Cont']?>)
                                </a>
                                </li>
                            <? } ?>
                        </ul>
                        </div>
                    </div>
              </div>
				
                
                
                <p class="align-center"><input type="button" value="Search Now" class="search_btn"></p>
            </div>
            <div class="clr"></div>
        </div>

  
 

