<?php 
global $mySessionFront;
$db=new Db();

?>

<!-- ================================== Pajing ======================================-->
<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
				$('#paging_container1').pajinate();
			});
</script>
<!-- =============================== End Pajing ======================================-->

<script>
$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
       // $('li#mypro').addClass('active');
		$('li#mypro').removeClass('active');
        });	 


$(document).ready(function() {
		$('textarea#editor1').addClass('ckeditor');
        });	

$(function() {
	$( "#user_dob22" ).datepicker({
	changeMonth: true,
	changeYear: true,
	dateFormat: 'yy-mm-dd'
	});
});		
		
</script>



<div class="container company_profile">
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->
<?php $res=$this->Company_Data; ?>

        	<div class="content_full">
            	<div class="job_head">
                	<div class="img">
                   	   <?php 
						if($res['user_image']=='')
						{
						?>
							<img width="124" height="118"  src="<?=IMAGES_URL?>no-avator.png" >
                        <?php }else{ ?>
							<img width="124" height="118" src="<?=ADMIN_IMG?>user_pic/<?php echo $res['user_image']?>" alt="">
						<? }?>
                    </div>
                    <div class="info">
                    	<h1 class="title captl"><?php echo $res['user_company']?></h1>
                        <div class="manage_profile"><a href="<?=BASE_PATH?>dashboard/companyedit/user_id/<?=$mySessionFront->user['FrontUserId']?>">Manage Profile</a></div>
                        <p class="font12"><?php echo $res['user_city']?>, <?php echo $res['country_name']?><!--San Francisco, California--> </p>
                        <p class="job_title"><span class="blue"><?php echo $res['category_title']?></span></p>
                        <div class="floatleft"><a href="<?=APPLICATION_URL?>subscription/index" class="blue">Add more Credits</a></div>
                        <div class="floatright"><a href="<?=APPLICATION_URL?>job/postjob" class="blue">Post New Job</a></div>
                    </div>
                    <div class="clr"></div>
                </div>
                
                <div class="list">
                	<div class="block2">
                    	<div class="block2_head">
                        	<h2 class="floatleft">Overview</h2>
                        	<div class="floatright"><!--<a href="#" class="edit_btn2">Edit</a>--></div>
                            <div class="clr"></div>
                        </div>
                        <div class="block2_content">
                            <p><?php echo $res['user_company_detail']?><!--We live with your dream to Create, inspire and Transform your Digital Identities into an emerging BRAND. We’re an Independent digital design, development and branding agency who strives to provide a better solution to all your business needs.--></p>
                            <ul class="list_3 font12">
                            	<li>
                                	<p class="blue upprcase">INDUSTRIES</p>
                                    <p><?php echo $res['category_title']?></p>
                                </li>
                                <li>
                                	<p class="blue upprcase">ANNUAL REVENUE</p>
                                    <p>$<?php echo $res['user_annual_revenue']?></p>
                                </li>
                                <li>
                                	<p class="blue upprcase">NUMBER OF EMPLOYEES</p>
                                    <p><?php echo $res['user_number_of_employees']?></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="tab_block">
                    	<ul class="tabs">
                        	<li id="manage_ac" class="active"><a href="<?=BASE_PATH?>dashboard/companyedit/user_id/<?=$mySessionFront->user['FrontUserId']?>">Manage Account</a></li>
                            <li id="my_credit"><a href="<?=BASE_PATH?>dashboard/mycredits" >My Credits</a></li>
                            <li id="pay_his"><a href="<?=BASE_PATH?>dashboard/paymenthistory" >Payment History</a></li>
                            <li id="pay_mthd"><a href="<?=BASE_PATH?>dashboard/paymentmethod" >Payment Method</a></li>
                        </ul>
                        <div class="tab_content company_profile_form">
                        	<ul class="in_tab">
<li class="active first"><a href="<?=BASE_PATH?>dashboard/companyedit/user_id/<?=$mySessionFront->user['FrontUserId']?>">Personal Information</a></li>
                                <li class=""><a href="<?=BASE_PATH?>dashboard/companyinfo/user_id/<?=$mySessionFront->user['FrontUserId']?>">Company information</a></li>
                            </ul>

                            <div class="in_tab_content selectForm jqtransformdone">
<!--========================================== LOADING AJAX INFORMATIONS ===================================================-->
<div id="load_data" >
 <form name="myform" id="myform" action="" method="post" enctype="multipart/form-data">                                   
<div class="fieldset1">
    <h2 class="legend">Personal Information</h2>
    <p class="align-right red">* Required Fields</p>
    
    <table width="100%" cellspacing="0" cellpadding="0" border="0">
        <tbody><tr>
                <td width="33%">Full Name (English): <span class="red">*</span><br><?php echo $this->myform->user_fname?></td>
                <td width="33%">Nationality <span class="red">*</span><br><?php echo $this->myform->Nationality_id?></td>
                <td>Birth Date <span class="red">*</span><br><?php echo $this->myform->user_dob?></td>
            </tr>
            <tr>
                <td class="radios">Gender <span class="red">*</span><br><span class="label">
                <?php echo $this->myform->user_gender?></span> </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </tbody></table>
</div>
<div class="fieldset1">
    <h2 class="legend">Contact Information</h2>
    <p class="align-right red">* Required Fields</p>
   
  	  <table width="100%" cellspacing="0" cellpadding="0" border="0">
        <tbody><tr>
                <td width="33%">Address (Line 1)<br><?php echo $this->myform->user_address_line_1?></td>
                <td width="33%">Address (Line 2)<br><?php echo $this->myform->user_address_line_2?></td>
                <td>P. O. Box <span class="red">*</span><br><?php echo $this->myform->user_po_box?></td>
            </tr>
            <tr>
                <td>Zip/Postal Code<br><?php echo $this->myform->user_zip?></td>
                <td>Residence Location<span class="red">*</span><br>
    <?php echo $this->myform->Country_id?>
    </td>
                <td>City <span class="red">*</span><br><?php echo $this->myform->user_city?></td>
            </tr>
            <tr>
                <td>Email Address: <span class="red">*</span><br><?php echo $this->myform->user_email?></td>
                <td colspan="2">Phone Number  <br>
					<?php echo $this->myform->user_phone_country_code?> 
                    <?php echo $this->myform->user_phone?>
                    <?php echo $this->myform->user_phone_extn_code?>
                    
               </td>
            </tr>
            <tr>
                <td class="pad0" colspan="3">
                    <table width="100%" cellspacing="0" cellpadding="0" border="0">
                        <tbody><tr>
                                <td width="65%">Evening-time Phone <br>
                                	<?php echo $this->myform->user_company_evening_phone_country_code?>
                                    <?php echo $this->myform->user_company_evening_phone?>
                                	<?php echo $this->myform->user_company_evening_phone_extension_code?>
                                </td>
                                <td>Mobile Phone <span class="red">*</span> <br>
                                <?php echo $this->myform->user_mobile_country_code?>
                                <?php echo $this->myform->user_mobile?>
                                </td>
                            </tr>
                            <tr>
                                <td>Fax <br>
                                	<?php echo $this->myform->user_fax_country_code?>
                                    <?php echo $this->myform->user_fax_number?>
                                    <?php echo $this->myform->user_fax_ext?>
                                    
                               </td>
                                
                                <td>WEBSITE  <br><?php echo $this->myform->user_company_web_url?></td>
                            </tr>
                        </tbody></table>
                </td>
            </tr>
        </tbody>
	</table>
    <div class="align-left">
    	<input type="submit" class="save_btn" name="mySubmit" id="mySubmit" value="save change" />
<!--        <a href="#" class="save_btn">save change</a>-->
    </div>
    
    <div class="clr"></div>
</div>
</form>
<!--========================================== LOADING AJAX INFORMATIONS ===================================================-->
</div>
                                
                            </div>
                        </div>
                        
                    </div>
                    <div class="clr"></div>
                </div>
            </div>
            <div class="clr"></div>
        </div>

