
                
<div class="profile_head">
                	<div class="img"><img src="images/profile_img1.png" alt=""></div>
                    <div class="info">
                    	<h1 class="title captl">Yousef Ali</h1>
                        <h3>Sr.Software Engineer at T3 Media</h3>
                        <div class="floatright edit_btn1">
                        	<a href="#">Save</a>
                        </div>
                        
                        <p class="font12 exp_edu1">San Francisco, California <span>|</span> Information Technologies and Services</p>
                        <ul class="exp_edu font12">
                        	<li><span>Current</span> T3 Media</li>
                           
                        </ul>
                    </div>
                    <div class="clr"></div>
                </div>
                
<div class="profiel_list">
                	<div class="block1 selectForm">
                    	<h2 class="floatleft title"><a href="#">Upload Resume</a></h2>
                        <span class="file-wrapper">
                          <input type="file" />
                          <span class="file-holder"></span>
                          <span class="button">Browse</span>
                        </span>
                        <div class="floatright pdf_icon">Convert to PDF <img src="images/pdf_icon.png" alt=""></div>
                        <div class="clr"></div>
                    </div>
                    <div class="block1">
                    	<h2 class="floatleft title">Profile Summery</h2>
                        <!--<div class="floatright"><a class="edit_btn2" href="#">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content" >
                        
                        	<img src="images/html_editer.jpg" width="100%" alt="">
                            <textarea rows="4" cols="10" class="textarea" id="Profile_Summery" ></textarea>
                        </div>
                        <!--<div class="floatright"><a class="edit_btn3" href="#">Save</a></div>-->
                        <div class="clr"></div>
                    </div>
                    <div class="block1 selectForm">
                    	<h2 class="floatleft title">Experience</h2>
                        <!--<div class="floatright"><a class="edit_btn2" href="#">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="bullet2">
                            	<li>
                                	<div class="number">1<a class="trash_icon" href="#"><img src="images/trash_icon.png" alt=""></a></div>
                                    <div class="info1 font12 edit_form">
                                    	<p>
                                        	<label>Job Title</label>
                                            <input type="text" class="inputbox" value="" placeholder="Operation Head">
                                        </p>
                                        <p>
                                        	<label>Company Name</label>
                                            <input type="text" class="inputbox" value="" placeholder="T3 Media">
                                        </p>
                                        <p>
                                        	<label>Location</label>
                                            <input type="text" class="inputbox" value="" placeholder="San Francisco, California">
                                        </p>
                                        <p>
                                        	<label>Job Responsibilities</label>
                                            <textarea rows="4" cols="10" class="textarea">Expert in business process engineering and software development life cycle, including analysis, design, development, testing and implementation of software applications.</textarea>
                                        </p>
                                        <p>
                                        	<label>Company Logo</label>
                                            <span class="file-wrapper">
                                              <input type="file" />
                                              <span class="file-holder"></span>
                                              <span class="button">Browse</span>
                                            </span>
                                        </p>
                                        <p>
                                        	<label>Employment Period </label>
                                            <select class="selectbox1"><option>2011</option></select> <select class="selectbox2"><option>2012</option></select>
                                        </p>
                                    </div>
                                    <div class="clr"></div>
                                </li>
                            </ul>
                            <p align="right"><a href="#"><img src="images/plus_icon.png" alt=""></a></p>
                        </div>
                        <!--<div class="floatright"><a class="edit_btn3" href="#">Save</a></div>-->
                        <div class="clr"></div>
                    </div>
                    <div class="block1">
                    	<h2 class="floatleft title">Skills &amp; Expertise</h2>
                        <!--<div class="floatright"><a class="edit_btn2" href="#">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<div class="edit_form">
                        		<textarea rows="4" cols="10" class="textarea">Expert in business process engineering and software development life cycle, including analysis, design, development, testing and implementation of software applications.</textarea>
                            </div>
                        </div>
                        <!--<div class="floatright"><a class="edit_btn3" href="#">Save</a></div>-->
                        <div class="clr"></div>
                    </div>
                    <div class="block1 selectForm">
                    	<h2 class="floatleft title">Education</h2>
                        <!--<div class="floatright"><a class="edit_btn2" href="#">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="bullet2">
                            	<li>
                                	<div class="number">1<a class="trash_icon" href="#"><img src="images/trash_icon.png" alt=""></a></div>
                                    <div class="info1 font12 edit_form">
                                    	<p>
                                        	<label><span class="red">*</span>Basic / Graduation:</label>
                                            <input type="text" class="inputbox" value="" placeholder="Operation Head">
                                        </p>
                                        <p>
                                        	<label><span class="red">*</span>University/Institute:</label>
                                            <input type="text" class="inputbox" value="" placeholder="Operation Head">
                                        </p>
                                        <p>
                                        	<label><span class="red">*</span>Dates Attended </label>
                                            <select class="selectbox1"><option>2011</option></select> <select class="selectbox2"><option>2012</option></select>
                                        </p>
                                    </div>
                                    <div class="clr"></div>
                                </li>
                            </ul>
                        </div>
                        <!--<div class="floatright"><a class="edit_btn3" href="#">Save</a></div>-->
                        <div class="clr"></div>
                    </div>
                    <div class="block1 selectForm">
                    	<h2 class="floatleft title">Personal Information</h2>
                        <!--<div class="floatright"><a class="edit_btn2" href="#">Edit</a></div>-->
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="view_list edit_form edit_form1">
                            	<li>
                                	<div class="label">Date of Birth</div>
                                    <div class="info"><input type="text" value="" class="inputbox" placeholder="20 April 1985"></div>
                                </li>
                                <li>
                                	<div class="label">Marital Status</div>
                                    <div class="info"><input type="text" value="" class="inputbox" placeholder="20 April 1985"></div>
                                </li>
                                <li>
                                	<div class="label">Email Address</div>
                                    <div class="info"><input type="text" value="" class="inputbox" placeholder="info@abc.com"></div>
                                </li>
                                <li>
                                	<div class="label">Phone Number</div>
                                    <div class="info"><input type="text" value="" class="inputbox" placeholder="+012345679891"></div>
                                </li>
                                <li>
                                	<div class="label">Gender</div>
                                    <div class="info"><select><option>Male</option></select></div>
                                </li>
                                <li>
                                	<div class="label">Nationality</div>
                                    <div class="info"><select><option>African</option></select></div>
                                </li>
                                <li>
                                	<div class="label">Career Level</div>
                                    <div class="info"><input type="text" value="" class="inputbox" placeholder="Not Mentioned"></div>
                                </li>
                                <li class="full">
                                	<hr>
                                    <div class="label"><strong>Change Password</strong></div>
                                </li>
                                <li>
                                	<div class="label">Old Password</div>
                                    <div class="info"><input type="password" value="123456" class="inputbox"></div>
                                </li>
                                <li>
                                	<div class="label">New Password</div>
                                    <div class="info"><input type="password" value="123456" class="inputbox"></div>
                                </li>
                                <li>
                                	<div class="label">Repeat Password</div>
                                    <div class="info"><input type="password" value="123456" class="inputbox"></div>
                                </li>
                            </ul>
                            <div class="clr"></div>
                        </div>
                        <div class="floatright"><a class="edit_btn3" href="#">Save</a></div>
                        <div class="clr"></div>
                    </div>
                </div>
