<?php 
global $mySessionFront;
$db=new Db();
?>

<!--============================================ Java Script & Css ===========================================-->	
<script src="<?=JS_URL?>jquery-1.5.js" type="text/javascript"></script>
<script language = "Javascript">
	//$(document).ready(function() {
         // $('body').addClass('home');
        //});
		
	$(document).ready(function() {
        $('li').removeClass('active');
        });	
		
$(function() {
	$( "#my_dob" ).datepicker({
	changeMonth: true,
	changeYear: true,
	dateFormat: 'yy-mm-dd'
	});
});
</script>

<!--============================================ End Java Script & Css ===========================================-->  


<div class="container register_page ">
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->
<?php if($_REQUEST['user_type']=='Employer') { ?>

<h1 class="title">Join over 40,000 employers who trust JOBPORTAL.com as their career partner</h1>
    <div class="floatleft highlight-box1">
        <h3>Why Choose jobportal .com?</h3>
        <ul class="check_icons">
            <li>Access to 12,250,000 qualified job seekers, anytime.</li>
            <li>5 million visits/month, giving your jobs top visibility.</li>
            <li>Friendly, on-the-ground support from our 12 regional offices.</li>
            <li>We speak Arabic, English, French.</li>
            <li>Solutions for all budgets, some even for free!</li>
        </ul>
    </div>
    <div class="floatright highlight-box1">
        <h3>Contact Options</h3>
        <ul class="icon_list">
            <li><img alt="" src="<?=APPLICATION_URL?>images/phone_icon.png"><br>+123.4.1234567</li>
            <li><img alt="" src="<?=APPLICATION_URL?>images/mail_icon.png"><br><a href="#">Email us</a></li>
        </ul>
    </div>
    <div class="clr"></div>
    <div class="seperator">&nbsp;</div>
    <h2 class="title">Register Using Your Email (it will only take a minute!)<span class="floatright orng">* Required Fields</span>.</h2>
 
<form name="myform" id="myform" enctype="multipart/form-data" action="" method="post">    
    <div class="form selectForm jqtransformdone">
        <table width="100%" cellspacing="0" cellpadding="0" border="0">
          <tbody><tr>
            <td>FIRST NAME <span class="red">*</span><br><?php echo $this->myform->user_fname?></td>
            <td>LAST NAME <span class="red">*</span><br><?php echo $this->myform->user_lname?></td>
            <td>EMAIL <span class="red">*</span><br><?php echo $this->myform->user_email?>
    <input type="hidden" name="user_type" id="user_type" value="<? echo $_REQUEST['user_type']?>" /></td>
          </tr>
          <tr>
            <td>COUNTRY <span class="red">*</span><br>
    <?php echo $this->myform->Country_id?>
    </td>
            <td>City <span class="red">*</span><br><?php echo $this->myform->user_city?></td>
             <td>Your Nationality <span class="red">*</span><br><?php echo $this->myform->Nationality_id?></td>
          </tr>
          <tr>
            <td>Your Birth Date <span class="red">*</span><br>
    <?php echo $this->myform->user_dob?>&nbsp;<!--<img src="<?=APPLICATION_URL?>images/Cal.gif" name="cmdbusinessunit" align="absmiddle" id="cmdbusinessunit" onclick="return displayCalendar(document.myform.user_dob,'dd-mm-yyyy',this)"/>-->
    </td>
            <td>GENDER <br><?php echo $this->myform->user_gender?></td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td class="radios" colspan="3">What's your language preference? <span class="red">*</span><br><br />
    <?php echo $this->myform->user_language_preference?>
    <!--<label><input type="radio" name="user_language_preference" value=""> English</label> 
    <label><input type="radio" name="user_language_preference" value=""> Arabic</label> 
    <label><input type="radio" name="user_language_preference" value=""> French</label>-->
    </td>
          </tr>
          <tr>
            <td colspan="3">
                <h3 class="blue">Login Information</h3>
            </td>
          </tr>
          <tr>
            <td>PASSWORD <span class="red">*</span><br>
    <?php echo $this->myform->user_password?>
    <!--<input type="text" value="" class="inputbox">-->
    </td>
   			<td>CONFIRM PASSWORD <br>
    <?php echo $this->myform->confirm_user_password?>
    <!--<input type="text" value="" class="inputbox">-->
    </td>
            <td>&nbsp;</td>
          </tr>
        </tbody></table>
        <p>By creating an account, you agree to our <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>.</p>
    </div>
    <div class="block_footer">
        <div class="floatleft"><input type="button" value="BACK" class="back" onclick="window.location.href='<?=APPLICATION_URL?>index/login'"></div>
        <div class="floatright"><input type="submit" value="CREATE AN ACCOUNT" class="submit" onclick=""></div>
        <div class="clr"></div>
    </div>
<!--<a href="DOWNLOADURL" onclick="javascript:window.location.href='http://analytics.performable.com'; return false;">TITLE OF DOWNLOAD</a>-->
</form>    
<div class="clr"></div>
        
<?php } else { ?>


<h1 class="title">Create a Free Account</h1>
<p class="font16">Get instant access to the tools necessary for finding a job in the Middle East.</p>
<div class="social_register">
    <label>SOCIAL SING UP</label>
    <a href="#"><img alt="" src="<?=APPLICATION_URL?>images/login_facebook.png"></a> <a href="#"><img alt="" src="<?=APPLICATION_URL?>images/login_twitter.png"></a>
</div>
<div class="seperator">
    <span class="or">or</span>
</div>
<h2 class="title">Register Using Your Email (it will only take a minute!)<span class="floatright orng">* Required Fields</span>.</h2>

<form name="myform" id="myform" enctype="multipart/form-data" action="" method="post">            
 <div class="form selectForm jqtransformdone">
                <table width="100%" cellspacing="0" cellpadding="0" border="0">
                  <tbody><tr>
                    <td>FIRST NAME <span class="red">*</span><br><?php echo $this->myform->user_fname?></td>
    				<td>LAST NAME <span class="red">*</span><br><?php echo $this->myform->user_lname?></td>
                    <td>
                   		 EMAIL <span class="red">*</span><br><?php echo $this->myform->user_email?>
                    	<input type="hidden" name="user_type" id="user_type" value="Job Seeker" />
                    </td>
                  </tr>
                  <tr>
                    <td>COUNTRY <span class="red">*</span><br>
						<?php echo $this->myform->Country_id?>
                    </td>
                    <td>City <span class="red">*</span><br><?php echo $this->myform->user_city?></td>
                    <td>Your Nationality <span class="red">*</span><br><?php echo $this->myform->Nationality_id?></td>
                  </tr>
                  <tr>
                    <td>Your Birth Date <span class="red">*</span><br>
					<?php echo $this->myform->user_dob?>&nbsp;<!--<img src="<?=APPLICATION_URL?>images/Cal.gif" name="cmdbusinessunit" align="absmiddle" id="cmdbusinessunit" onclick="return displayCalendar(document.myform.user_dob,'dd-mm-yyyy',this)"/>-->
                    
                    <!--<input type="text" value="" placeholder="YY/MM/DD" class="inputbox">-->
                    </td>
                    <td>GENDER <br><?php echo $this->myform->user_gender?></td>
                    <td>&nbsp;</td>
                  </tr>
                  <tr>
                    <td class="radios" colspan="3">What's your language preference? <span class="red">*</span><br><br />
						<?php echo $this->myform->user_language_preference?>
                        <!--<label><input type="radio" name="user_language_preference" value=""> English</label> 
                        <label><input type="radio" name="user_language_preference" value=""> Arabic</label> 
                        <label><input type="radio" name="user_language_preference" value=""> French</label>-->
                    </td>
                  </tr>
                  <tr>
                  	<td colspan="3">
                    	<h3 class="blue">Login Information</h3>
                    </td>
                  </tr>
                  <tr>
                    <td>PASSWORD <span class="red">*</span><br>
						<?php echo $this->myform->user_password?>
                    	<!--<input type="text" value="" class="inputbox">-->
                    </td>
                    <td>CONFIRM PASSWORD <br>
                   		 <?php echo $this->myform->confirm_user_password?>
                    	<!--<input type="text" value="" class="inputbox">-->
                    </td>
                    <td>&nbsp;</td>
                  </tr>
                </tbody></table>
                <p>By creating an account, you agree to our Terms of Use and Privacy Policy.</p>
            </div>
 <div class="block_footer">
                <div class="floatleft"><input type="button" value="BACK" class="back" onclick="window.location.href='<?=APPLICATION_URL?>index/login'"></div>
                <div class="floatright"><input type="submit" value="CREATE AN ACCOUNT" class="submit" onclick=""></div>
                <div class="clr"></div>
            </div>
 <div class="clr"></div>   
</form>               
<? } ?>
</div>