<?php 
 	global $mySessionFront;
	$db=new Db();

?>
<script src="<?=JS_URL?>jquery-1.5.js" type="text/javascript"></script>
<script language = "Javascript">
	//$(document).ready(function() {
         // $('body').addClass('home');
        //});
		
	$(document).ready(function() {
        $('li').removeClass('active');
        });	
		
$(function() {
	$( "#my_dob" ).datepicker({
	changeMonth: true,
	changeYear: true,
	dateFormat: 'yy-mm-dd'
	});
});
</script>

<div class="container login_page" >
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================--> 
 
    <h1 class="title">MANAGE ACCOUNT</h1>
    <div class="block  full">
        <h2 class="title">Reset Password</h2>
<form name="myform" id="myform" enctype="multipart/form-data" action="" method="post"> 
		<div class="ftrd_form">
            <p>Please Enter your New Password</p>
            <p>
                <label>Email Address *</label>
               <!-- <input type="text" class="inputbox" value="" style="width:300px;" id="user_email" name="user_email">-->
                <?php echo $this->myform->user_password?>
            </p>
            <p>
                <label>Email Address *</label>
               <!-- <input type="text" class="inputbox" value="" style="width:300px;" id="user_email" name="user_email">-->
                <?php echo $this->myform->confirm_password?>
            </p>
          
            <div class="form_btns form_btns1 floatright">
            <input type="submit" class="save_job_btn" value="Submit" onclick="forgetpass();">
        </div>
        
            <p>Required Fields *</p>
     </div>
</form>
    </div>
    <div class="clr"></div>
</div>

 