<?php 
global $mySessionFront;
$db=new Db();

$akash=$this->user_id;
$aid=@$akash['user_id'];
?>

<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
				$('#paging_container1').pajinate();
			});
</script>
<script type="text/javascript" language="javascript">
	$(document).ready(function() {
          $('body').removeClass('home');
        });
	
	$(document).ready(function() {
        $('li#home').removeClass('active');
        });	
				
	$(document).ready(function() {
        $('li#mypro').addClass('active');
        });	 
		  
</script>
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->

<div class="container job_apply">
        	<div class="content_left">
            <?php 
				$res=$this->UserData;			
			?>
            	<div class="profile_head">
                	<div class="img">
                    	<img width="167" height="167" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                    </div>
                    <div class="info">
                    	<h1 class="title captl"><? echo $res['user_fname'].' '.$res['user_lname']?></h1>
                        <h3>Sr.Software Engineer at T3 Media</h3>
                        <p class="font12 exp_edu1">San Francisco, California <span>|</span> Information Technologies and Services</p>
                        <ul class="exp_edu font12">
                        	<li><span>Current</span> T3 Media</li>
                            <li><span>Current</span> T3 Media</li>
                            <li><span>Current</span> T3 Media</li>
                        </ul>
                    </div>
                    <div class="clr"></div>
                </div>
             
               
                
                <div class="list">
            <h1 class="title captl floatleft">View All Jobs</h1>
            
            	<div class="clr"></div>
            
            
           	<div id="paging_container1">
            <ul class="content">
               <?php if($mySessionFront->user['userRole']=='Employer') { ?>
			   <? if(is_array($this->Save_Job_List) && count($this->Save_Job_List) > 0) {
					foreach($this->Save_Job_List as $Myjob) { ?>	 
                <li>
                    <div class="list_block">
                    	<div class="head font12">
                            <div class="floatleft">
                                <h4><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$Myjob['id']?>" class="black"><?=$Myjob['job_title']?></a></h4>
                                <p><?=$Myjob['user_company']?> - <span class="blue"><?=$Myjob['user_fname']?>, <?=$Myjob['user_lname']?></span></p>
                            </div>
                            <div class="floatright">
                                <p><?php echo date("d-m-Y", strtotime($Myjob['job_saved_on']))?></p>
                                
                            </div>
                        </div>
                        <p class="clr font12"><?=substr($Myjob['job_description'],0,186)?>...</p>
                        <div class="footer font11">
                        	 <span>Job Role: <strong class="blue"><?=$Myjob['job_role_title']?></strong></span>
                             <span>Company Industry: <strong class="blue"><?=$Myjob['category_title']?></strong></span>
                             <span>Career Level: <strong class="blue"><?=$Myjob['career_level_title']?></strong></span>
                        </div>
                    </div>
                </li>
                 <?php } ?>
                 <?php } else {?> 
                <li>
               		<div class="list_block">
                        
                        <div class="footer font11">
                             <h4>No Job Found</h4> 
                        </div>
                    </div>
                </li>
                 <?php } } else { ?>
                 
                 <?  //========== Job Seekar ===========//
				 	if(is_array($this->Save_Job_List) && count($this->Save_Job_List) > 0) {
					foreach($this->Save_Job_List as $Myjob) { ?>	 
                <li>
                    <div class="list_block">
                    	<div class="head font12">
                            <div class="floatleft">
                                <h4><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$Myjob['id']?>" class="black"><?=$Myjob['job_title']?></a></h4>
                                <p><?=$Myjob['user_company']?> - <span class="blue"><?=$Myjob['user_fname']?>, <?=$Myjob['user_lname']?></span></p>
                            </div>
                            <div class="floatright">
                                <p><?php echo date("d-m-Y", strtotime($Myjob['job_saved_on']))?></p>
                                
                            </div>
                        </div>
                        <p class="clr font12"><?=substr($Myjob['job_description'],0,186)?>...</p>
                        <div class="footer font11">
                        	 <span>Job Role: <strong class="blue"><?=$Myjob['job_role_title']?></strong></span>
                             <span>Company Industry: <strong class="blue"><?=$Myjob['category_title']?></strong></span>
                             <span>Career Level: <strong class="blue"><?=$Myjob['career_level_title']?></strong></span>
                        </div>
                    </div>
                </li>
                 <? } ?>
                 <? } else { ?> 
                <li>
               		<div class="list_block">
                        
                        <div class="footer font11">
                             <h4>No Job Found</h4> 
                        </div>
                    </div>
                </li>
                 <? } }?>
                 
            </ul>
            <div class="page_navigation" style="padding-left:125px;"></div>	
            <!--<div class="paging">
                <ul>
                    <li><a href="#">Prev</a></li>
                    <li><span>1</span></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
            </div>-->
            </div>
        </div>
            </div>
            <div class="content_right">
            	<div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyApply_Job=$this->Apply_Job;
							$MyTotalSave=$this->SaveJobs; 
							$MyTotalNoti=$this->Job_Noti;
						?>
                    <ul>
                    	<li><span class="number number_green"><?php echo $MyApply_Job['TotalApply']?></span>Apply Jobs</a></li>
                         <li><a href="<?=APPLICATION_URL?>user/jobsaved"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
                        <li><a href="#"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
                        <li><a href="#"><span class="number">45</span> Profile Views</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
                <div class="block recommended font12">
                	<h2 class="title">Recommended Jobs</h2>
                    <ul>
						<?php 
                            $i=1;
                            foreach($this->Rec_Job as $MyRec_Job) {
                        ?>
                    	<li>
                        	<div class="img">
                            	<?php 
								if($MyRec_Job['user_image']=='')
								{
								?>
									 <img width="100" height="70"  src="<?=IMAGES_URL?>no-avator.png" >
									
								<?php }else{ ?>
									 <img width="100" height="70" src="<?=ADMIN_IMG?>user_pic/<?php echo $MyRec_Job['user_image']?>" alt="">
								<? }?>
                            </div>
                            <div class="info">
                            	<h3><?php echo $MyRec_Job['job_title']?></h3>
                                <p><strong>Posted by</strong> <?php echo $MyRec_Job['user_company']?> for <?php echo $MyRec_Job['job_city']?></p>
                                <p><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$MyRec_Job['id']?>" class="blue1">View &amp; Apply</a> - <?php echo date("d-m-Y", strtotime($MyRec_Job['job_posted_on']))?></p>
                            </div>
                        </li>
                        <?php } ?>
                        <li class="align-right"><a href="<?=APPLICATION_URL?>user/alljobs" class="black">View All →</a></li>
                    </ul>
                </div>
                <div class="block ad align-center"><img alt="" src="images/google_ad1.jpg"></div>
                <div class="block ad align-center"><img alt="" src="images/google_ad2.jpg"></div>
            </div>
            <div class="clr"></div>
        </div>

