<?php 
global $mySessionFront;
$db=new Db();

if($mySessionFront->user['userRole']=='Job Seeker') { 
		$res=$this->UserData;
?>
<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->
		<div id="pro_edit">
                	<div class="job_head">
                	<div class="img">
                    	<img width="124" height="118" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                        </div>
                    <div class="info">
                    	<h1 class="title captl"><?php echo $res['user_company']?></h1>
                        <div class="manage_profile">
<a onclick="getajax('<?=BASE_PATH?>user/companyprofile/user_id/<?=$mySessionFront->user['FrontUserId']?>','pro_edit');" href="javascript:void(0)" >Manage Profile</a>

						</div>
                        <p class="font12"><?php echo $res['user_city']?>, <?php echo $res['country_name']?> </p>
                        <p class="job_title"><span class="blue">Software Development</span></p>
                        <div class="floatleft"><a href="#" class="black">Add more Credits</a></div>
                        <div class="floatright"><a href="<?=APPLICATION_URL?>job/postjob" class="blue">Post New Job</a></div>
                    </div>
                    <div class="clr"></div>
                </div>
                </div>
   <? 
		//echo "Hello Job Seeker";
	} else {  $res=$this->UserData;
	
	?>
   
	<div id="pro_edit">
                	<div class="job_head">
                	<div class="img">
                    	<img width="124" height="118" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                        </div>
                    <div class="info">
                    	<h1 class="title captl"><?php echo $res['user_company']?></h1>
                        <div class="manage_profile">
<a onclick="getajax('<?=BASE_PATH?>user/companyprofile/user_id/<?=$mySessionFront->user['FrontUserId']?>','pro_edit');" href="javascript:void(0)" >Manage Profile</a>

						</div>
                        <p class="font12"><?php echo $res['user_city']?>, <?php echo $res['country_name']?> </p>
                        <p class="job_title"><span class="blue">Software Development</span></p>
                        <div class="floatleft"><a href="#" class="black">Add more Credits</a></div>
                        <div class="floatright"><a href="<?=APPLICATION_URL?>job/postjob" class="blue">Post New Job</a></div>
                    </div>
                    <div class="clr"></div>
                </div>
                </div>
	
	<? } ?>
  
 

