<?php 
global $mySessionFront;
$db=new Db();

$akash=$this->user_id;
$aid=@$akash['user_id'];
?>

<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
				$('#paging_container1').pajinate();
			});
			

</script>


<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->

<div class="container job_apply">
    <div class="content_left">
        <?php 
				$res=$this->UserData;			
			?>
            	<div class="profile_head">
                	<div class="img">
                    	<img width="167" height="167" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                    </div>
                    <div class="info">
                    	<h1 class="title captl"><? echo $res['user_fname'].' '.$res['user_lname']?></h1>
                        <h3>Sr.Software Engineer at T3 Media</h3>
                        <p class="font12 exp_edu1">San Francisco, California <span>|</span> Information Technologies and Services</p>
                        
                    </div>
                    <div class="clr"></div>
                </div>
        
        <div class="list">
            <h1 class="title captl floatleft">My Job Posting</h1>
            
            	<div class="clr"></div>
            
            
           	<div id="paging_container1">
            <ul class="content">
              
                 
                 <?  //========== Job Seekar ===========//
				 	if(is_array($this->Post_Job_List) && count($this->Post_Job_List) > 0) {
					foreach($this->Post_Job_List as $Myjob) { ?>	 
                <li>
                    <div class="list_block">
                            <div class="head font12">
                                <div class="floatleft">
									<h4><a href="<?=APPLICATION_URL?>user/applieduser/id/<?=$Myjob['id']?>" class="black"><?=$Myjob['job_title']?></a></h4>
                                    <p><?=$Myjob['job_city']?>- <span class="blue"><?=$Myjob['country_name']?></span></p>
                                </div>
                                <div class="floatright">
                                    <p><?php echo date("d-m-Y", strtotime($Myjob['job_posted_on']))?></p>
							<?	
                            
                            $Post_Applied = $db->runQuery("SELECT COUNT(id) as TotalApply FROM tbl_applied_jobs WHERE job_id = '".$Myjob['id']."' ");	
                                foreach($Post_Applied as $MyPost_Applied)
                                { 
                            ?>
                                    <p><strong class="orng"><?php echo $MyPost_Applied['TotalApply'] ?> Applied</strong></p>
                                    <? }?>
                                </div>
                            </div>
                            <p class="clr font12"><?=substr($Myjob['job_description'],0,186)?>...</p>
        <div class="footer font11">
             <span style="margin-right:-14px;">Job Role: <strong class="blue"><?=$Myjob['job_role_title']?></strong></span>
             <span style="margin-right:-14px;">Company Industry: <strong class="blue"><?=$Myjob['category_title']?></strong></span>
             <span>Career Level: <strong class="blue"><?=$Myjob['career_level_title']?></strong></span>
        </div>
                        </div>
                </li>
                 <? } ?>
                 <? } else { ?> 
                <li>
               		<div class="list_block">
                        
                        <div class="footer font11">
                             <h4>No Job Found</h4> 
                        </div>
                    </div>
                </li>
                 <? } ?>
                 
            </ul>
            <div class="page_navigation" style="padding-left:125px;"></div>	
            <!--<div class="paging">
                <ul>
                    <li><a href="#">Prev</a></li>
                    <li><span>1</span></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
            </div>-->
            </div>
        </div>
    </div>
    
    <div class="content_right">
        <div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyPosted_Job=$this->Posted_Job;
							$MyTotalSave=$this->SaveJobs; 
							$MyTotalNoti=$this->Job_Noti;
						?>
                    <ul>
   <li><a href="<?=APPLICATION_URL?>user/jobposted"><span class="number number_green"><?php echo $MyPosted_Job['TotalApply']?></span>Jobs Posted</a></li>
   <li><a href="<?=APPLICATION_URL?>user/jobsaved"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
   <li><a href="<?=APPLICATION_URL?>user/notification"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
   <li><a href="<?=APPLICATION_URL?>user/alljobs"><span class="number">10</span> Resumes</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
        <div class="block recommended font12">
                	<h2 class="title">My Jobs</h2>
                    <ul>
						<?php 
                            $i=1;
                            foreach($this->Rec_Job as $MyRec_Job) {
                        ?>
                    	<li>
                        	<div class="img">
                            	<img width="100" height="70" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                            </div>
                            <div class="info">
                            	<h3><?php echo $MyRec_Job['job_title']?></h3>
                                <p><strong>Posted by</strong> <?php echo $MyRec_Job['user_company']?> for <?php echo $MyRec_Job['job_city']?></p>
                                <p><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$MyRec_Job['id']?>" class="blue1">View &amp; Apply</a> - <?php echo date("d-m-Y", strtotime($MyRec_Job['job_posted_on']))?></p>
                            </div>
                        </li>
                        <?php } ?>
                        <li class="align-right"><a href="<?=APPLICATION_URL?>user/alljobs" class="black">View All →</a></li>
                    </ul>
                </div>
        <div class="block ad align-center"><img src="<?=IMAGES_URL?>google_ad1.jpg" alt=""></div>
        <div class="block ad align-center"><img src="<?=IMAGES_URL?>google_ad2.jpg" alt=""></div>
    </div>
    <div class="clr"></div>
</div>

