<?php 
global $mySessionFront;
$db=new Db();

$akash=$this->user_id;
$aid=@$akash['user_id'];
?>

<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate_1.js" type="text/javascript"></script>

<script language = "Javascript">
function sendmsg(){
	//alert('Hello...');
	var UserMsg=$("#UserMsg").val();
	alert(UserMsg);
	var sendto=$("#sendto").val();
	alert(sendto);
	
	var msgid=$("#msgid").val();
	alert(msgid);
	
	document.getElementById('message').innerHTML="<img src='<?=APPLICATION_URL_ADMIN?>images/load.gif' border='0'>";
	$.ajax({ url: "<?php echo $this->url(array('controller'=>'user','action'=>'sendmsg'),'default',true);?>",
	type: "POST",
	data: ({msgid: msgid, sendto: sendto,UserMsg: UserMsg}),
	success: function(data){			
	//$("#showDiv").html(data);
	$("#message").html(data);			
	}});
//alert('hello');
}
</script>

<script>
$(document).ready(function(){
	$('#paging_container1').pajinate();
				
});
</script>
<script>
$(document).ready(function(){
	$('#MyInbox').click(function ( event ) {
        $("#MyInbox").addClass("active");
        $("#MySentbox").removeClass("active");
        event.preventDefault(); 
       
   });
    
	$('#MySentbox').click(function ( event ) {
        $("#MySentbox").addClass("active");
        $("#MyInbox").removeClass("active");
        event.preventDefault(); 
        
   });			
			
});
			

</script>
<script src="<?=JS_URL?>ddaccordion.js"></script>
<script type="text/javascript">


ddaccordion.init({
	headerclass: "submenuheader", //Shared CSS class name of headers group
	contentclass: "submenu", //Shared CSS class name of contents group
	revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click", "clickgo", or "mouseover"
	mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
	collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
	defaultexpanded: [], //index of content(s) open by default [index1, index2, etc] [] denotes no content
	onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
	animatedefault: false, //Should contents open by default be animated into view?
	persiststate: true, //persist state of opened contents within browser session?
	toggleclass: ["", ""], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
	togglehtml: ["suffix", "<img src='images/drop-down-erro2.jpg' class='statusicon' />", "<img src='images/drop-down-erro.jpg' class='statusicon' />"], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
	animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
	oninit:function(headers, expandedindices){ //custom code to run when headers have initalized
		//do nothing
	},
	onopenclose:function(header, index, state, isuseractivated){ //custom code to run whenever a header is opened or closed
		//do nothing
	}
})


</script>

<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->





<div class="container job_apply">
    <div class="content_left">
        	<?php 
			  $res=$this->UserData;			
			?>
            	<div class="profile_head">
                	<div class="img">
                    	<img width="167" height="167" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                    </div>
                    <div class="info">
                    	<h1 class="title captl"><? echo $res['user_fname'].' '.$res['user_lname']?></h1>
                        <h3>Sr.Software Engineer at T3 Media</h3>
                        <p class="font12 exp_edu1">San Francisco, California <span>|</span> Information Technologies and Services</p>
                        <ul class="exp_edu font12">
                        	<li><span>Current</span> T3 Media</li>
                            <li><span>Current</span> T3 Media</li>
                            <li><span>Current</span> T3 Media</li>
                        </ul>
                    </div>
                    <div class="clr"></div>
                </div>
        
        
            
        <div class="list">
        			<div id="ajaxDiv" style="visibility:hidden;"></div>
                    
                	<h1 class="title captl floatleft">Notifications</h1>
                    
                    <div class="clr"></div>
                    
                   
                   
                   
                    <ul class="content_tabs">
                    	<li class="active" id="MyInbox" onclick=""><a href="#">Inbox</a></li>
                        <li class="" id="MySentbox"><a href="#" >Sent</a></li>
                    </ul>
                    <div class="clr"></div>
                    
                    <!--==========================================================-->
                   		<div class="font11">
                        	<div id="paging_container1">
                                <ul class="ntfcn_list content">
                                   <?php if($mySessionFront->user['userRole']=='Employer') { ?>
                                   <? if(is_array($this->Inbox) && count($this->Inbox) > 0) {
                                        foreach($this->Inbox as $MyInbox) { ?>	 
                                         <li class="">
                                            
                                    <div class="submenuheader">
                                        <?php if($MyInbox['is_read']==0)
                                             {
                                        ?>
                               <div style="font-weight:bold;" onclick="getajax('<?=BASE_PATH?>user/isread/id/<?php echo $MyInbox['id']?>','','ajaxDiv');">
                                            <?php }else{ ?>
                                            <div>
                                            <?php } ?>
                                                <?=$MyInbox['user_fname']?> <?=$MyInbox['user_lname']?> 
                                                <span style="margin-left:20px;"><?=substr($MyInbox['subject'],0,10)?>...</span>
                                                <span style="margin-left:20px;"><?=substr($MyInbox['message'],0,45)?>...</span>
                                                <span style="margin-left:20px;"><?=$MyInbox['sent_on']?></span>
                                            </div> 
                                    
                                     </div>
                                      <div class="submenu" id="message"> 
                                      		<br />
                                            <div class="" ><?=$MyInbox['message']?></div>
                                            <br />
                                <div style="border-top:1px solid #CCC;" >
<form>
    <input type="hidden" name="sendto" id="sendto" value="<?=$MyInbox['from']?>" /><?php //echo $MyInbox['id']?>
    <textarea name="" cols="" class="mytextarea" name="UserMsg" rows="" id="UserMsg" ></textarea>
</form>
    <input type="button"  value="Sent Msg" class="apply_btn" onclick="sendmsg();">
								 </div> 
                                 
                                 
                                    </li>
                                 <?php } ?>
                                 <?php } else {?> 
                                    <li class="unread">
                                        <div class="title">No Notification Found</div>
                                    </li>
                                <?php } } else { ?>
                     
                                 <?  //========== Job Seekar ===========//
                                    if(is_array($this->Inbox) && count($this->Inbox) > 0) {
                                    foreach($this->Inbox as $MyInbox) { ?>
                                    	 
                                        
                                        	
                                    <li class="">
                                            
                                    <div class="submenuheader">
                                        <?php if($MyInbox['is_read']==0)
                                             {
                                        ?>
                               <div style="font-weight:bold;" onclick="getajax('<?=BASE_PATH?>user/isread/id/<?php echo $MyInbox['id']?>','','ajaxDiv');">
                                            <?php }else{ ?>
                                            <div>
                                            <?php } ?>
                                                <?=$MyInbox['user_fname']?> <?=$MyInbox['user_lname']?> 
                                                <span style="margin-left:20px;"><?=substr($MyInbox['subject'],0,10)?>...</span>
                                                <span style="margin-left:20px;"><?=substr($MyInbox['message'],0,45)?>...</span>
                                                <span style="margin-left:20px;"><?=$MyInbox['sent_on']?></span>
                                            </div> 
                                    
                                     </div>
                                     
                                     
                                      <div class="submenu" id="message"> 

                                      		<br />
                                            <div class="" ><?=$MyInbox['message']?></div>
                                            <br />
                                <div style="border-top:1px solid #CCC;" >
<form>
    <input type="hidden" name="sendto" id="sendto" value="<?=$MyInbox['from']?>" />
	<input type="hidden" name="msgid" id="msgid" value="<?=$MyInbox['id']?>" />
    <textarea name="" cols="" class="mytextarea" name="UserMsg" rows="" id="UserMsg" ></textarea>
</form>
    <input type="button"  value="Sent Msg" class="apply_btn" onclick="sendmsg();">
								 </div> 
                                 
                                 
                                    </li>                 
                                     <? } } else { ?> 
                                        <li class="unread">
                                            <div class="title">No Notification Found</div>
                                        </li>
                                     <? } }?>
                                </ul>
                                <div class="page_navigation" style="padding-left:125px;"></div>	
                             </div>
                    	</div>
                        
                    <!--==========================================================-->
                   
                 	</div>
        
                
    </div>
    <div class="content_right">
        <div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyApply_Job=$this->Apply_Job;
							$MyTotalSave=$this->SaveJobs; 
							$MyTotalNoti=$this->Job_Noti;
						?>
                    <ul>
                    	<li><a href="<?=APPLICATION_URL?>user/jobsapplied"><span class="number number_green"><?php echo $MyApply_Job['TotalApply']?></span>Apply Jobs</a></li>
                         <li><a href="<?=APPLICATION_URL?>user/jobsaved"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
                        <li><a href="<?=APPLICATION_URL?>user/notification"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
                        <li><a href="<?=APPLICATION_URL?>user/alljobs"><span class="number">45</span> Profile Views</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
        <div class="block recommended font12">
                	<h2 class="title">Recommended Jobs</h2>
                    <ul>
						<?php 
                            $i=1;
                            foreach($this->Rec_Job as $MyRec_Job) {
                        ?>
                    	<li>
                        	<div class="img">
                            	<img width="100" height="70" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                            </div>
                            <div class="info">
                            	<h3><?php echo $MyRec_Job['job_title']?></h3>
                                <p><strong>Posted by</strong> <?php echo $MyRec_Job['user_company']?> for <?php echo $MyRec_Job['job_city']?></p>
                                <p><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$MyRec_Job['id']?>" class="blue1">View &amp; Apply</a> - <?php echo date("d-m-Y", strtotime($MyRec_Job['job_posted_on']))?></p>
                            </div>
                        </li>
                        <?php } ?>
                        <li class="align-right"><a href="<?=APPLICATION_URL?>user/alljobs" class="black">View All →</a></li>
                    </ul>
                </div>
        <div class="block ad align-center"><img src="<?=IMAGES_URL?>google_ad1.jpg" alt=""></div>
        <div class="block ad align-center"><img src="<?=IMAGES_URL?>google_ad2.jpg" alt=""></div>
    </div>
    <div class="clr"></div>
</div>

