<?php 
global $mySessionFront;
$db=new Db();

?>

<script src="<?=JS_URL?>jquery.min.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery.pajinate.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
				$('#paging_container1').pajinate();
			});
			

</script>


<!--================================================ Error Message ===========================================-->
<div id="divError">
	<?php if(isset($mySessionFront->errorMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->errorMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->errorMsg);} ?>
    
    <?php if(isset($mySessionFront->sucMsg)){ ?>
    <div id="message-green">
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
	<tbody><tr>
		<td class="green-left">
        	<?php echo $mySessionFront->sucMsg; ?>
        </td>
		<td class="green-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';" class="close-green">
        	<img alt="" src="<?=IMAGES_URL?>icon_close_green.gif">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->sucMsg); } ?>
    
    <?php if(isset($mySessionFront->warningMsg)){ ?>
    <div id="message-red">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tbody><tr>
		<td class="red-left">
        <?php echo $mySessionFront->warningMsg; ?>
        </td>
		<td class="red-right">
        <a onclick="Javascript:document.getElementById('divError').style.display='none';">
        	<img src="<?=IMAGES_URL?>icon_close_red.gif" alt="">
        </a>
        </td>
	</tr>
	</tbody></table>
	</div>
    <?php unset($mySessionFront->warningMsg); } ?>
</div>
<!--============================================ end Error Message ===========================================-->
<?php 
	$res=$this->UserData;
?>
<div class="container job_apply">
        	<div class="content_left">
            	
                    <div id="pro_edit">
                       <div class="job_head">
                        <div class="img">
		                    <img width="120" height="120" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
        	            </div>
                        <div class="info">
                            <h1 class="title captl"><? echo $res['user_fname'].' '.$res['user_lname']?></h1>
                           
                            
                            <div class="floatright edit_btn1">
                    
                            </div>
                             <p class="font12 exp_edu1">
                                 <div class="font12">Phone Number   <?php echo $res['user_phone']?></div>
                                 <div class="font12 ">Email Address <?php echo $res['user_email']?></div>
                                 <?php echo $res['user_city']?>, <?php //echo $res['country_name']?> <span>|</span> <?php echo $res['country_name']?>
                             </p>
                            
                        </div>
                        <div class="clr"></div>
                    </div>
                    </div>
               
                
                
                <div class="profiel_list">
                	
                     <div class="block1" id="pro_summary">
                    	<h2 class="floatleft title">Profile Summery</h2>
                        <div class="floatright">
                        </div>
                        <div class="clr"></div>
                        <div class="block1_content">
                        <div id="ckedit">
                        <!--<textarea class="ckeditor" cols="80" id="editor1" rows="5" tabindex="1"></textarea>-->
						</div>
							<?php echo $res['user_profile_summary']?>
                        </div>
                    </div>
                    
                   
                    <div class="block1" id="experience">
                      <h2 class="floatleft title">Experience</h2>
                       <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="bullet2">
                            	<?php 
									$i=1;
									foreach($this->User_Experience as $MyUser_Experience) {
								?>
                              	  <li>
                                	<div class="number"><?=$i++;?></div>
                                    <div class="info">
                                    	<h2><?php echo $MyUser_Experience['position']?></h2>
                                        <h3><?php echo $MyUser_Experience['company']?></h3>
                                        <p class="font12"><?php echo $MyUser_Experience['location']?>, <?php echo $MyUser_Experience['country_name']?> <span class="pipe_space">|</span> <?php echo $MyUser_Experience['employment_period_from']?> &ndash; <?php echo $MyUser_Experience['employment_period_to']?></p>
                                        <h4>Job Responsibilities</h4>
                                        <p class="font12"><?php echo $MyUser_Experience['responsibility']?></p>
                                    </div>
                                    <div class="img">
                                    
									<?php 
                                        if($MyUser_Experience['logo']=='')
                                        {
                                    ?>
                                		<img width="112" height="70"  src="<?=IMAGES_URL?>company_logo1.jpg" name="logo">
                                        
                                    <?php } else{ ?>
                               			 <img width="100" height="70" src="<?=USER_PIC?><?php echo $MyUser_Experience['logo']?>" alt="">
                                	<? }?>
                                    	
                                     </div>
									<div class="clr"></div>
                                </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>

                    <div class="block1" id="skills">
                    	<h2 class="floatleft title">Skills &amp; Expertise</h2>
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<p class="font16"><?php echo $res['user_skills_n_expertise']?> </p>
                        </div>
                    </div> 
                    <div class="block1" id="education">
                    	<h2 class="floatleft title">Education</h2>
                        <div class="floatright">
						</div>
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="bullet2">
                            <?php 
									$i=1;
									foreach($this->Education_Dashboard as $User_Education) {
								?>
                              <li>
                                	<div class="number"><?=$i++;?></div>
                                    <div class="info1">
                                    	<h2><?php echo $User_Education['university']?></h2>
                                        <h3><?php echo $User_Education['education_title']?></h3>

                                  <p class="font12">
                                  	From <?php echo $User_Education['starting_year']?> to <?php echo $User_Education['finishing_year']?>
                                    
                                  </p>

                                    </div>
                                    
                                    <div class="clr"></div>
                                </li>
                             <?php } ?>   
                            </ul>
                        </div>
                        
                    </div>
                    <!--Personal Information-->
                    <div class="block1" id="personal">
                    	<h2 class="floatleft title">Personal Information</h2>
                        <div class="floatright">

                        </div>
                        <div class="clr"></div>
                        <div class="block1_content">
                        	<ul class="view_list">
                            	<li>
                                	<div class="label">Date of Birth</div>

                                    <div class="info"><?php echo date("d-M-Y", strtotime($res['user_dob']))?></div>
                                </li>
                                
                                <li>
                                	<div class="label">Marital Status</div>
                                    <div class="info"><?php echo $res['user_marital_status']?></div>
                                </li>
                                <li>
                                	<div class="label">Email Address</div>
                                    <div class="info"><?php echo $res['user_email']?></div>
                                </li>
                                <li>
                                	<div class="label">Phone Number</div>
                                    <div class="info"><?php echo $res['user_phone']?></div>
                                </li>
                                <li>
                                	<div class="label">Gender</div>
                                    <div class="info"><?php echo $res['user_gender']?></div>
                                </li>
                                <li>
                                	<div class="label">Nationality</div>
                                    <div class="info"><?php echo $res['nation_title']?></div>
                                </li>
                                <li>
                                	<div class="label">Career Level</div>
                                    <div class="info"><?php echo $res['career_level_title']?></div>
                                </li>
                            </ul>
                            <div class="clr"></div>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="content_right">
            	<div class="block stats">
                	<h2 class="title">Profile Stats</h2>
                    	<?php 	
							$MyPosted_Job=$this->Posted_Job;
							$MyTotalSave=$this->SaveJobs; 
							$MyTotalNoti=$this->Job_Noti;
						?>
                    <ul>
   <li><a href="<?=APPLICATION_URL?>user/jobposted"><span class="number number_green"><?php echo $MyPosted_Job['TotalApply']?></span>Jobs Posted</a></li>
   <li><a href="<?=APPLICATION_URL?>user/jobsaved"><span class="number"><?php echo $MyTotalSave['TotalSave']?></span> Jobs Saved</a></li>
   <li><a href="<?=APPLICATION_URL?>user/notification"><span class="number"><?php echo $MyTotalNoti['TotalNoti']?></span> Notifications</a></li>
   <li><a href="<?=APPLICATION_URL?>user/alljobs"><span class="number">10</span> Resumes</a></li>
                    </ul>
                    <div class="clr"></div>
                </div>
                <!--Recommended Jobs-->
                <div class="block recommended font12">
                	<h2 class="title">My Jobs</h2>
                    <ul>
						<?php 
                            $i=1;
                            foreach($this->Rec_Job as $MyRec_Job) {
                        ?>
                    	<li>
                        	<div class="img">
                            	<img width="100" height="70" src="<?=USER_PIC?><?php echo $res['user_image']?>" alt="">
                            </div>
                            <div class="info">
                            	<h3><?php echo $MyRec_Job['job_title']?></h3>
                                <p><strong>Posted by</strong> <?php echo $MyRec_Job['user_company']?> for <?php echo $MyRec_Job['job_city']?></p>
                                <p><a href="<?=APPLICATION_URL?>job/jobdetail/id/<?=$MyRec_Job['id']?>" class="blue1">View &amp; Apply</a> - <?php echo date("d-m-Y", strtotime($MyRec_Job['job_posted_on']))?></p>
                            </div>
                        </li>
                        <?php } ?>
                        <li class="align-right"><a href="<?=APPLICATION_URL?>user/alljobs" class="black">View All →</a></li>
                    </ul>
                </div>
                <div class="block ad align-center"><img alt="" src="images/google_ad1.jpg"></div>
                <div class="block ad align-center"><img alt="" src="images/google_ad2.jpg"></div>
            </div>
            <div class="clr"></div>
        </div>


