<?
global $mySession;

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" >
<?php	
	if($this->pagetitle==''){
		$pgt  = 'Joky.';
	} else {
		$pgt = $this->pagetitle;
	}
	$cnname = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$actname = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<head>
<script>var APPLICATION_URL = '<? echo APPLICATION_URL?>';</script>

<script>var IMAGES_URL = '<? echo APPLICATION_URL.'images/?>';</script>
<?php /*?><script language="javascript" src="<? echo JS_URL?>main.js"></script><?php */?>
<title><?php echo $pgt;?></title>

<script src="<?=JS_URL?>jquery.timers-1.0.0.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<? echo CSS_URL?>stylesheet.css"/>

<script src="<?=JS_URL?>dhtmlgoodies_calendar.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<? echo CSS_URL?>dhtmlgoodies_calendar.css"/>

<script src="<?=JWPLAY?>jwplayer.js" type="text/javascript"></script>
<!--<script type="text/javascript">jwplayer.key="tvXbjKzyjOpdE395WPP6hBkFJZL0BU4RXNWb7Q==";</script>
-->


<script src="<?=VIDIO_PLYER?>flowplayer-3.2.6.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>


<script src="<?=SLIDING_LOGIN?>js/slide.js" type="text/javascript"></script>
<script src="<?=SLIDING_LOGIN?>js/jquery-1.3.2.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<? echo SLIDING_LOGIN?>css/slide.css"/>

<script>
	$(function() {
		$( "#accordion" ).accordion();
	});
</script>


<script type="text/javascript"> 
var curr_lb_div; 
var is_modal = false; 
 
	function ShowLightBoxmail1(lb_div, isModal) 
	{ 
    	document.getElementById(lb_div).style.display='block'; 
	    document.getElementById('fade1').style.display='block'; 
	    curr_lb_div = lb_div; 
	    	if (isModal) 
	        	is_modal = true; 
	    	else is_modal = false; 
	} 
	 
	function HideLightBoxmail() 
	{ 
	    if (document.getElementById(curr_lb_div)) 
	    { 
	         document.getElementById(curr_lb_div).style.display='none'; 
	         document.getElementById('fade1').style.display='none'; 
	         curr_lb_div1 = ''; 
			// uploadcomment();
	    } 
	} 
	</script>

<script src="<?=JS_URL?>ddaccordion.js" type="text/javascript"></script>
<script src="<?=JS_URL?>jquery-1.4.2.min.js" type="text/javascript"></script>


</head>
<body>
<section class="wraper">
<aside class="main">

<!--header----------->
<header>
<!----top-part-------->
	<?php include "new_header.phtml"; ?>
</header>
<!--header---end----->

<!---------nav------->
<nav>
<?php include "menu.phtml"; ?>

</nav>
<?php /*?><!--nav---end----->
<?
	if(isLogged())
	{
?>
<figure class="banner"><img src="images/banner.jpg"/></div>
<? } else {?>
<figure class="banner"><img src="images/banner.jpg"/></figure>
<? } ?><?php */?>

<div class="middle-contact-bg">
<div id="errorDiv" style="padding-bottom:5px; border:solid 0px #FF0000;">
	<?php  
        if(isset($mySession->errorMsg)){ 
            echo errorMsg($mySession->errorMsg);
            unset($mySession->errorMsg); 
        } 
        if(isset($mySession->sucMsg)){ 
            echo sucessMsg($mySession->sucMsg);
            unset($mySession->sucMsg); 
        } 
        if(isset($mySession->warningMsg)){ 
            echo warningMsg($mySession->warningMsg);
            unset($mySession->warningMsg); 
        }
    ?>
</div>
        
<?php echo $this->layout()->content; ?>

</div>

</aside>

<footer>
<?php include "footer.phtml"; ?>

</footer>
</section>





</body>
</html>