
<div class="main">
<div class="footer-bg">

<nav class="menu">
<ul>
<li><a href="#">Home</a></li>
<li><a href="#">Comedian Event</a></li>
<li><a href="#">Marketing</a></li>
<li><a href="#">Services</a></li>
<li><a href="#">Contact Us</a></li>
</ul>
</nav>

<div class="copy-right">Copyright &copy; Asia infosolution Pvt Ltd. All Rights Reserved</div>
<div class="powrd">Powerd By : </div>
<div class="footer-logo"><img src="<?=IMAGES_URL?>footer-logo.png"/></div>
</div>



</div>


