<?php 
global $mySession;
?>
<form name="pass_edit" id="pass_edit" action="<?php echo $this->url(array('controller'=>'index', 'action'=>'changepassword','ak'=>@$this->ak), 'default', true)?>" method="post">      
    
         <table width="100%" border="0" cellspacing="5" cellpadding="0" class="frmtable">
      <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
      <? if($this->chps) { ?>  
        <tr>
            <td width="172" align="left" valign="middle" style="padding-left:5px;padding-top:5px;">
                Old Password :            </td>
            <td width="768" align="left" valign="top" style="padding-top:5px;">
                <?php echo $this->changeup->_oldpass;?>            </td>		
        </tr>
		 <tr>
            <td width="172" align="left" valign="middle" style="padding-left:5px;padding-top:5px;">
                New Password :            </td>
            <td width="768" align="left" valign="top" style="padding-top:5px;">
                <?php echo $this->changeup->_pass;?>            </td>		
        </tr>
        <tr>
            <td width="172" align="left" valign="middle" style="padding-left:5px;padding-top:5px;">
                Confirm Password :            </td>
            <td width="768" align="left" valign="top" style="padding-top:5px;">
                <?php echo $this->changeup->_cpass;?>            </td>		
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
  
  <tr><td>&nbsp;</td>
    <td>
	<input type="submit" name="subm" id="subm" value="Submit" /><?php //echo $this->Form->submit?></td>
   
    
  </tr>
  <? } else { ?>
  <tr><td><br />
<br />
<br />
<br />
<br />
<br />
<br />
</td></tr>
  <? } ?>
  
  
</table>

  </form>

	<!--<div style="vertical-align:middle;padding-top:100px;" align="center">WELCOME TO RAJASTHAN BUILD SQUARE INDIA LIMITED</div>-->

 

